#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

#include <QPushButton>
#include <QComboBox>
#include <QGroupBox>
#include <QCheckBox>
#include <QGridLayout>
#include <QLabel>
#include <QSpinBox>
#include <QLineEdit>
#include <QDateTimeEdit>
#include <QTextEdit>
#include <QScrollArea>
#include <QNetworkSession>
#include <QUuid>

#include <QtNetwork>

#include "uuid/uuid.h"


/**
 * type definitions
 */
typedef unsigned char byte;


class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

    QWidget *guiWidget;
    QScrollArea *guiScrollArea;


    QVBoxLayout *mainLayout;

    // Header
    QGroupBox *headerGBox;
    QGridLayout *headerLayout;

    QGroupBox *headerSgRequestGroupBox;
    QHBoxLayout *headerSgRequestHBoxLayout;
    QCheckBox *headerSgRequestClientCheckBox;
    QCheckBox *headerSgRequestGatewayCheckBox;
    QCheckBox *headerSgRequestFree1CheckBox;
    QCheckBox *headerSgRequestFree2CheckBox;
    QCheckBox *headerSgRequestFree3CheckBox;
    QCheckBox *headerSgRequestFree4CheckBox;
    QCheckBox *headerSgRequestFree5CheckBox;
    QCheckBox *headerSgRequestFree6CheckBox;

    QGroupBox *headerSgProfileGroupBox;
    QHBoxLayout *headerSgProfileHBoxLayout;
    QCheckBox *headerSgProfileClientCheckBox;
    QCheckBox *headerSgProfileGatewayCheckBox;
    QCheckBox *headerSgProfileFree1CheckBox;
    QCheckBox *headerSgProfileFree2CheckBox;
    QCheckBox *headerSgProfileFree3CheckBox;
    QCheckBox *headerSgProfileFree4CheckBox;
    QCheckBox *headerSgProfileFree5CheckBox;
    QCheckBox *headerSgProfileFree6CheckBox;

    QLabel *headerVersionMajorLbl;
    QSpinBox *headerVersionMajorSpBx;
    QLabel *headerVersionMinorLbl;
    QSpinBox *headerVersionMinorSpBx;

    QLabel *headerChannelLbl;
    QSpinBox *headerChannelSpBx;

    QPushButton *headerUuidRefreshBtn;
    QLineEdit *headerUuidLnEd;

    QLabel *headerIpAddressLbl;
    QComboBox *headerIpAddressCBx;

    QLabel *headerIpPortLbl;
    QComboBox *headerIpPortCBx;

    QPushButton *headerCreationTimeRefreshBtn;
    QDateTimeEdit *headerCreationTimeEdit;

    QLabel *headerAdditionalTypeLbl;
    QSpinBox *headerAdditionalTypeSpBx;

    QLabel *headerAdditionalSizeLbl;
    QSpinBox *headerAdditionalSizeSpBx;
    QPushButton *headerAdditionalSizeRefreshBtn;

    QLabel *headerServiceLbl;
    QComboBox *headerServiceCBx;

    // Context
    QGroupBox *contextGBox;
    QGridLayout *contextLayout;

    QLabel *contextTypeLbl;
    QSpinBox *contextTypeSpBx;

    QLabel *contextContentLbl;
    QSpinBox *contextContentSpBx;

    QLabel *contextMaskLbl;
    QSpinBox *contextMaskSpBx;

    QLabel *contextAdditionalSizeLbl;
    QSpinBox *contextAdditionalSizeSpBx;
    QPushButton *contextAdditionalSizeRefreshBtn;


    // Data
    QGridLayout *dataLayout;

    QGroupBox *dataGBox;
    QLabel *dataTypeLbl;
    QComboBox *dataTypeCBx;
    QLabel *dataLbl;
    QTextEdit *dataTxtEd;

    QLabel *dataAdditionalSizeLbl;
    QSpinBox *dataAdditionalSizeSpBx;
    QPushButton *dataAdditionalSizeRefreshBtn;


    // GuiInteraction
    QVBoxLayout *interactionLayout;
    QGroupBox *interactionGBox;

    QGridLayout *actionLayout;

    QPushButton *sendBtn;

    uuid_t sourceUuid;

    QUuid uuid;


    void printBits(size_t const size, void const * const ptr);

public slots:
    void refreshUuid();
    void refreshTime();
    void refreshAdditionalHeader();
    void refreshAdditionalContextBricks();
    void limitTextLength();
    void refreshAdditionalData();
    void sendContext();
    void readTcpAnswer();
    void readUdpAnswer();
    void displayError(QAbstractSocket::SocketError socketError );

    void updateIpPort(int index);

private:
    QUdpSocket *udpSocket;
    QTcpSocket *tcpSocket;
    quint16 blockSize;

public:    
    QLabel *dynamicHeaderLbl_1;
    QSpinBox *dynamicHeaderSpBx_1;
    QLabel *dynamicHeaderLbl_2;
    QSpinBox *dynamicHeaderSpBx_2;
    QLabel *dynamicHeaderLbl_3;
    QSpinBox *dynamicHeaderSpBx_3;
    QLabel *dynamicHeaderLbl_4;
    QSpinBox *dynamicHeaderSpBx_4;
    QLabel *dynamicHeaderLbl_5;
    QSpinBox *dynamicHeaderSpBx_5;
    QLabel *dynamicHeaderLbl_6;
    QSpinBox *dynamicHeaderSpBx_6;
    QLabel *dynamicHeaderLbl_7;
    QSpinBox *dynamicHeaderSpBx_7;
    QLabel *dynamicHeaderLbl_8;
    QSpinBox *dynamicHeaderSpBx_8;
    QLabel *dynamicHeaderLbl_9;
    QSpinBox *dynamicHeaderSpBx_9;
    QLabel *dynamicHeaderLbl_10;
    QSpinBox *dynamicHeaderSpBx_10;

//    QLabel *dynamicHeaderLbl_11;
//    QSpinBox *dynamicHeaderSpBx_11;
//    QLabel *dynamicHeaderLbl_12;
//    QSpinBox *dynamicHeaderSpBx_12;
//    QLabel *dynamicHeaderLbl_13;
//    QSpinBox *dynamicHeaderSpBx_13;
//    QLabel *dynamicHeaderLbl_14;
//    QSpinBox *dynamicHeaderSpBx_14;
//    QLabel *dynamicHeaderLbl_15;
//    QSpinBox *dynamicHeaderSpBx_15;
//    QLabel *dynamicHeaderLbl_16;
//    QSpinBox *dynamicHeaderSpBx_16;
//    QLabel *dynamicHeaderLbl_17;
//    QSpinBox *dynamicHeaderSpBx_17;
//    QLabel *dynamicHeaderLbl_18;
//    QSpinBox *dynamicHeaderSpBx_18;
//    QLabel *dynamicHeaderLbl_19;
//    QSpinBox *dynamicHeaderSpBx_19;
//    QLabel *dynamicHeaderLbl_20;
//    QSpinBox *dynamicHeaderSpBx_20;
//    QLabel *dynamicHeaderLbl_21;
//    QSpinBox *dynamicHeaderSpBx_21;
//    QLabel *dynamicHeaderLbl_22;
//    QSpinBox *dynamicHeaderSpBx_22;
//    QLabel *dynamicHeaderLbl_23;
//    QSpinBox *dynamicHeaderSpBx_23;
//    QLabel *dynamicHeaderLbl_24;
//    QSpinBox *dynamicHeaderSpBx_24;
//    QLabel *dynamicHeaderLbl_25;
//    QSpinBox *dynamicHeaderSpBx_25;
//    QLabel *dynamicHeaderLbl_26;
//    QSpinBox *dynamicHeaderSpBx_26;
//    QLabel *dynamicHeaderLbl_27;
//    QSpinBox *dynamicHeaderSpBx_27;
//    QLabel *dynamicHeaderLbl_28;
//    QSpinBox *dynamicHeaderSpBx_28;
//    QLabel *dynamicHeaderLbl_29;
//    QSpinBox *dynamicHeaderSpBx_29;
//    QLabel *dynamicHeaderLbl_30;
//    QSpinBox *dynamicHeaderSpBx_30;
//    QLabel *dynamicHeaderLbl_31;
//    QSpinBox *dynamicHeaderSpBx_31;
//    QLabel *dynamicHeaderLbl_32;
//    QSpinBox *dynamicHeaderSpBx_32;
//    QLabel *dynamicHeaderLbl_33;
//    QSpinBox *dynamicHeaderSpBx_33;
//    QLabel *dynamicHeaderLbl_34;
//    QSpinBox *dynamicHeaderSpBx_34;
//    QLabel *dynamicHeaderLbl_35;
//    QSpinBox *dynamicHeaderSpBx_35;
//    QLabel *dynamicHeaderLbl_36;
//    QSpinBox *dynamicHeaderSpBx_36;
//    QLabel *dynamicHeaderLbl_37;
//    QSpinBox *dynamicHeaderSpBx_37;
//    QLabel *dynamicHeaderLbl_38;
//    QSpinBox *dynamicHeaderSpBx_38;
//    QLabel *dynamicHeaderLbl_39;
//    QSpinBox *dynamicHeaderSpBx_39;
//    QLabel *dynamicHeaderLbl_40;
//    QSpinBox *dynamicHeaderSpBx_40;
//    QLabel *dynamicHeaderLbl_41;
//    QSpinBox *dynamicHeaderSpBx_41;
//    QLabel *dynamicHeaderLbl_42;
//    QSpinBox *dynamicHeaderSpBx_42;
//    QLabel *dynamicHeaderLbl_43;
//    QSpinBox *dynamicHeaderSpBx_43;
//    QLabel *dynamicHeaderLbl_44;
//    QSpinBox *dynamicHeaderSpBx_44;
//    QLabel *dynamicHeaderLbl_45;
//    QSpinBox *dynamicHeaderSpBx_45;
//    QLabel *dynamicHeaderLbl_46;
//    QSpinBox *dynamicHeaderSpBx_46;
//    QLabel *dynamicHeaderLbl_47;
//    QSpinBox *dynamicHeaderSpBx_47;
//    QLabel *dynamicHeaderLbl_48;
//    QSpinBox *dynamicHeaderSpBx_48;
//    QLabel *dynamicHeaderLbl_49;
//    QSpinBox *dynamicHeaderSpBx_49;
//    QLabel *dynamicHeaderLbl_50;
//    QSpinBox *dynamicHeaderSpBx_50;
//    QLabel *dynamicHeaderLbl_51;
//    QSpinBox *dynamicHeaderSpBx_51;
//    QLabel *dynamicHeaderLbl_52;
//    QSpinBox *dynamicHeaderSpBx_52;
//    QLabel *dynamicHeaderLbl_53;
//    QSpinBox *dynamicHeaderSpBx_53;
//    QLabel *dynamicHeaderLbl_54;
//    QSpinBox *dynamicHeaderSpBx_54;
//    QLabel *dynamicHeaderLbl_55;
//    QSpinBox *dynamicHeaderSpBx_55;
//    QLabel *dynamicHeaderLbl_56;
//    QSpinBox *dynamicHeaderSpBx_56;
//    QLabel *dynamicHeaderLbl_57;
//    QSpinBox *dynamicHeaderSpBx_57;
//    QLabel *dynamicHeaderLbl_58;
//    QSpinBox *dynamicHeaderSpBx_58;
//    QLabel *dynamicHeaderLbl_59;
//    QSpinBox *dynamicHeaderSpBx_59;
//    QLabel *dynamicHeaderLbl_60;
//    QSpinBox *dynamicHeaderSpBx_60;
//    QLabel *dynamicHeaderLbl_61;
//    QSpinBox *dynamicHeaderSpBx_61;
//    QLabel *dynamicHeaderLbl_62;
//    QSpinBox *dynamicHeaderSpBx_62;
//    QLabel *dynamicHeaderLbl_63;
//    QSpinBox *dynamicHeaderSpBx_63;
//    QLabel *dynamicHeaderLbl_64;
//    QSpinBox *dynamicHeaderSpBx_64;
//    QLabel *dynamicHeaderLbl_65;
//    QSpinBox *dynamicHeaderSpBx_65;
//    QLabel *dynamicHeaderLbl_66;
//    QSpinBox *dynamicHeaderSpBx_66;
//    QLabel *dynamicHeaderLbl_67;
//    QSpinBox *dynamicHeaderSpBx_67;
//    QLabel *dynamicHeaderLbl_68;
//    QSpinBox *dynamicHeaderSpBx_68;
//    QLabel *dynamicHeaderLbl_69;
//    QSpinBox *dynamicHeaderSpBx_69;
//    QLabel *dynamicHeaderLbl_70;
//    QSpinBox *dynamicHeaderSpBx_70;
//    QLabel *dynamicHeaderLbl_71;
//    QSpinBox *dynamicHeaderSpBx_71;
//    QLabel *dynamicHeaderLbl_72;
//    QSpinBox *dynamicHeaderSpBx_72;
//    QLabel *dynamicHeaderLbl_73;
//    QSpinBox *dynamicHeaderSpBx_73;
//    QLabel *dynamicHeaderLbl_74;
//    QSpinBox *dynamicHeaderSpBx_74;
//    QLabel *dynamicHeaderLbl_75;
//    QSpinBox *dynamicHeaderSpBx_75;
//    QLabel *dynamicHeaderLbl_76;
//    QSpinBox *dynamicHeaderSpBx_76;
//    QLabel *dynamicHeaderLbl_77;
//    QSpinBox *dynamicHeaderSpBx_77;
//    QLabel *dynamicHeaderLbl_78;
//    QSpinBox *dynamicHeaderSpBx_78;
//    QLabel *dynamicHeaderLbl_79;
//    QSpinBox *dynamicHeaderSpBx_79;
//    QLabel *dynamicHeaderLbl_80;
//    QSpinBox *dynamicHeaderSpBx_80;
//    QLabel *dynamicHeaderLbl_81;
//    QSpinBox *dynamicHeaderSpBx_81;
//    QLabel *dynamicHeaderLbl_82;
//    QSpinBox *dynamicHeaderSpBx_82;
//    QLabel *dynamicHeaderLbl_83;
//    QSpinBox *dynamicHeaderSpBx_83;
//    QLabel *dynamicHeaderLbl_84;
//    QSpinBox *dynamicHeaderSpBx_84;
//    QLabel *dynamicHeaderLbl_85;
//    QSpinBox *dynamicHeaderSpBx_85;
//    QLabel *dynamicHeaderLbl_86;
//    QSpinBox *dynamicHeaderSpBx_86;
//    QLabel *dynamicHeaderLbl_87;
//    QSpinBox *dynamicHeaderSpBx_87;
//    QLabel *dynamicHeaderLbl_88;
//    QSpinBox *dynamicHeaderSpBx_88;
//    QLabel *dynamicHeaderLbl_89;
//    QSpinBox *dynamicHeaderSpBx_89;
//    QLabel *dynamicHeaderLbl_90;
//    QSpinBox *dynamicHeaderSpBx_90;
//    QLabel *dynamicHeaderLbl_91;
//    QSpinBox *dynamicHeaderSpBx_91;
//    QLabel *dynamicHeaderLbl_92;
//    QSpinBox *dynamicHeaderSpBx_92;
//    QLabel *dynamicHeaderLbl_93;
//    QSpinBox *dynamicHeaderSpBx_93;
//    QLabel *dynamicHeaderLbl_94;
//    QSpinBox *dynamicHeaderSpBx_94;
//    QLabel *dynamicHeaderLbl_95;
//    QSpinBox *dynamicHeaderSpBx_95;
//    QLabel *dynamicHeaderLbl_96;
//    QSpinBox *dynamicHeaderSpBx_96;
//    QLabel *dynamicHeaderLbl_97;
//    QSpinBox *dynamicHeaderSpBx_97;
//    QLabel *dynamicHeaderLbl_98;
//    QSpinBox *dynamicHeaderSpBx_98;
//    QLabel *dynamicHeaderLbl_99;
//    QSpinBox *dynamicHeaderSpBx_99;
//    QLabel *dynamicHeaderLbl_100;
//    QSpinBox *dynamicHeaderSpBx_100;
//    QLabel *dynamicHeaderLbl_101;
//    QSpinBox *dynamicHeaderSpBx_101;
//    QLabel *dynamicHeaderLbl_102;
//    QSpinBox *dynamicHeaderSpBx_102;
//    QLabel *dynamicHeaderLbl_103;
//    QSpinBox *dynamicHeaderSpBx_103;
//    QLabel *dynamicHeaderLbl_104;
//    QSpinBox *dynamicHeaderSpBx_104;
//    QLabel *dynamicHeaderLbl_105;
//    QSpinBox *dynamicHeaderSpBx_105;
//    QLabel *dynamicHeaderLbl_106;
//    QSpinBox *dynamicHeaderSpBx_106;
//    QLabel *dynamicHeaderLbl_107;
//    QSpinBox *dynamicHeaderSpBx_107;
//    QLabel *dynamicHeaderLbl_108;
//    QSpinBox *dynamicHeaderSpBx_108;
//    QLabel *dynamicHeaderLbl_109;
//    QSpinBox *dynamicHeaderSpBx_109;
//    QLabel *dynamicHeaderLbl_110;
//    QSpinBox *dynamicHeaderSpBx_110;
//    QLabel *dynamicHeaderLbl_111;
//    QSpinBox *dynamicHeaderSpBx_111;
//    QLabel *dynamicHeaderLbl_112;
//    QSpinBox *dynamicHeaderSpBx_112;
//    QLabel *dynamicHeaderLbl_113;
//    QSpinBox *dynamicHeaderSpBx_113;
//    QLabel *dynamicHeaderLbl_114;
//    QSpinBox *dynamicHeaderSpBx_114;
//    QLabel *dynamicHeaderLbl_115;
//    QSpinBox *dynamicHeaderSpBx_115;
//    QLabel *dynamicHeaderLbl_116;
//    QSpinBox *dynamicHeaderSpBx_116;
//    QLabel *dynamicHeaderLbl_117;
//    QSpinBox *dynamicHeaderSpBx_117;
//    QLabel *dynamicHeaderLbl_118;
//    QSpinBox *dynamicHeaderSpBx_118;
//    QLabel *dynamicHeaderLbl_119;
//    QSpinBox *dynamicHeaderSpBx_119;
//    QLabel *dynamicHeaderLbl_120;
//    QSpinBox *dynamicHeaderSpBx_120;
//    QLabel *dynamicHeaderLbl_121;
//    QSpinBox *dynamicHeaderSpBx_121;
//    QLabel *dynamicHeaderLbl_122;
//    QSpinBox *dynamicHeaderSpBx_122;
//    QLabel *dynamicHeaderLbl_123;
//    QSpinBox *dynamicHeaderSpBx_123;
//    QLabel *dynamicHeaderLbl_124;
//    QSpinBox *dynamicHeaderSpBx_124;
//    QLabel *dynamicHeaderLbl_125;
//    QSpinBox *dynamicHeaderSpBx_125;
//    QLabel *dynamicHeaderLbl_126;
//    QSpinBox *dynamicHeaderSpBx_126;
//    QLabel *dynamicHeaderLbl_127;
//    QSpinBox *dynamicHeaderSpBx_127;
//    QLabel *dynamicHeaderLbl_128;
//    QSpinBox *dynamicHeaderSpBx_128;
//    QLabel *dynamicHeaderLbl_129;
//    QSpinBox *dynamicHeaderSpBx_129;
//    QLabel *dynamicHeaderLbl_130;
//    QSpinBox *dynamicHeaderSpBx_130;
//    QLabel *dynamicHeaderLbl_131;
//    QSpinBox *dynamicHeaderSpBx_131;
//    QLabel *dynamicHeaderLbl_132;
//    QSpinBox *dynamicHeaderSpBx_132;
//    QLabel *dynamicHeaderLbl_133;
//    QSpinBox *dynamicHeaderSpBx_133;
//    QLabel *dynamicHeaderLbl_134;
//    QSpinBox *dynamicHeaderSpBx_134;
//    QLabel *dynamicHeaderLbl_135;
//    QSpinBox *dynamicHeaderSpBx_135;
//    QLabel *dynamicHeaderLbl_136;
//    QSpinBox *dynamicHeaderSpBx_136;
//    QLabel *dynamicHeaderLbl_137;
//    QSpinBox *dynamicHeaderSpBx_137;
//    QLabel *dynamicHeaderLbl_138;
//    QSpinBox *dynamicHeaderSpBx_138;
//    QLabel *dynamicHeaderLbl_139;
//    QSpinBox *dynamicHeaderSpBx_139;
//    QLabel *dynamicHeaderLbl_140;
//    QSpinBox *dynamicHeaderSpBx_140;
//    QLabel *dynamicHeaderLbl_141;
//    QSpinBox *dynamicHeaderSpBx_141;
//    QLabel *dynamicHeaderLbl_142;
//    QSpinBox *dynamicHeaderSpBx_142;
//    QLabel *dynamicHeaderLbl_143;
//    QSpinBox *dynamicHeaderSpBx_143;
//    QLabel *dynamicHeaderLbl_144;
//    QSpinBox *dynamicHeaderSpBx_144;
//    QLabel *dynamicHeaderLbl_145;
//    QSpinBox *dynamicHeaderSpBx_145;
//    QLabel *dynamicHeaderLbl_146;
//    QSpinBox *dynamicHeaderSpBx_146;
//    QLabel *dynamicHeaderLbl_147;
//    QSpinBox *dynamicHeaderSpBx_147;
//    QLabel *dynamicHeaderLbl_148;
//    QSpinBox *dynamicHeaderSpBx_148;
//    QLabel *dynamicHeaderLbl_149;
//    QSpinBox *dynamicHeaderSpBx_149;
//    QLabel *dynamicHeaderLbl_150;
//    QSpinBox *dynamicHeaderSpBx_150;
//    QLabel *dynamicHeaderLbl_151;
//    QSpinBox *dynamicHeaderSpBx_151;
//    QLabel *dynamicHeaderLbl_152;
//    QSpinBox *dynamicHeaderSpBx_152;
//    QLabel *dynamicHeaderLbl_153;
//    QSpinBox *dynamicHeaderSpBx_153;
//    QLabel *dynamicHeaderLbl_154;
//    QSpinBox *dynamicHeaderSpBx_154;
//    QLabel *dynamicHeaderLbl_155;
//    QSpinBox *dynamicHeaderSpBx_155;
//    QLabel *dynamicHeaderLbl_156;
//    QSpinBox *dynamicHeaderSpBx_156;
//    QLabel *dynamicHeaderLbl_157;
//    QSpinBox *dynamicHeaderSpBx_157;
//    QLabel *dynamicHeaderLbl_158;
//    QSpinBox *dynamicHeaderSpBx_158;
//    QLabel *dynamicHeaderLbl_159;
//    QSpinBox *dynamicHeaderSpBx_159;
//    QLabel *dynamicHeaderLbl_160;
//    QSpinBox *dynamicHeaderSpBx_160;
//    QLabel *dynamicHeaderLbl_161;
//    QSpinBox *dynamicHeaderSpBx_161;
//    QLabel *dynamicHeaderLbl_162;
//    QSpinBox *dynamicHeaderSpBx_162;
//    QLabel *dynamicHeaderLbl_163;
//    QSpinBox *dynamicHeaderSpBx_163;
//    QLabel *dynamicHeaderLbl_164;
//    QSpinBox *dynamicHeaderSpBx_164;
//    QLabel *dynamicHeaderLbl_165;
//    QSpinBox *dynamicHeaderSpBx_165;
//    QLabel *dynamicHeaderLbl_166;
//    QSpinBox *dynamicHeaderSpBx_166;
//    QLabel *dynamicHeaderLbl_167;
//    QSpinBox *dynamicHeaderSpBx_167;
//    QLabel *dynamicHeaderLbl_168;
//    QSpinBox *dynamicHeaderSpBx_168;
//    QLabel *dynamicHeaderLbl_169;
//    QSpinBox *dynamicHeaderSpBx_169;
//    QLabel *dynamicHeaderLbl_170;
//    QSpinBox *dynamicHeaderSpBx_170;
//    QLabel *dynamicHeaderLbl_171;
//    QSpinBox *dynamicHeaderSpBx_171;
//    QLabel *dynamicHeaderLbl_172;
//    QSpinBox *dynamicHeaderSpBx_172;
//    QLabel *dynamicHeaderLbl_173;
//    QSpinBox *dynamicHeaderSpBx_173;
//    QLabel *dynamicHeaderLbl_174;
//    QSpinBox *dynamicHeaderSpBx_174;
//    QLabel *dynamicHeaderLbl_175;
//    QSpinBox *dynamicHeaderSpBx_175;
//    QLabel *dynamicHeaderLbl_176;
//    QSpinBox *dynamicHeaderSpBx_176;
//    QLabel *dynamicHeaderLbl_177;
//    QSpinBox *dynamicHeaderSpBx_177;
//    QLabel *dynamicHeaderLbl_178;
//    QSpinBox *dynamicHeaderSpBx_178;
//    QLabel *dynamicHeaderLbl_179;
//    QSpinBox *dynamicHeaderSpBx_179;
//    QLabel *dynamicHeaderLbl_180;
//    QSpinBox *dynamicHeaderSpBx_180;
//    QLabel *dynamicHeaderLbl_181;
//    QSpinBox *dynamicHeaderSpBx_181;
//    QLabel *dynamicHeaderLbl_182;
//    QSpinBox *dynamicHeaderSpBx_182;
//    QLabel *dynamicHeaderLbl_183;
//    QSpinBox *dynamicHeaderSpBx_183;
//    QLabel *dynamicHeaderLbl_184;
//    QSpinBox *dynamicHeaderSpBx_184;
//    QLabel *dynamicHeaderLbl_185;
//    QSpinBox *dynamicHeaderSpBx_185;
//    QLabel *dynamicHeaderLbl_186;
//    QSpinBox *dynamicHeaderSpBx_186;
//    QLabel *dynamicHeaderLbl_187;
//    QSpinBox *dynamicHeaderSpBx_187;
//    QLabel *dynamicHeaderLbl_188;
//    QSpinBox *dynamicHeaderSpBx_188;
//    QLabel *dynamicHeaderLbl_189;
//    QSpinBox *dynamicHeaderSpBx_189;
//    QLabel *dynamicHeaderLbl_190;
//    QSpinBox *dynamicHeaderSpBx_190;
//    QLabel *dynamicHeaderLbl_191;
//    QSpinBox *dynamicHeaderSpBx_191;
//    QLabel *dynamicHeaderLbl_192;
//    QSpinBox *dynamicHeaderSpBx_192;
//    QLabel *dynamicHeaderLbl_193;
//    QSpinBox *dynamicHeaderSpBx_193;
//    QLabel *dynamicHeaderLbl_194;
//    QSpinBox *dynamicHeaderSpBx_194;
//    QLabel *dynamicHeaderLbl_195;
//    QSpinBox *dynamicHeaderSpBx_195;
//    QLabel *dynamicHeaderLbl_196;
//    QSpinBox *dynamicHeaderSpBx_196;
//    QLabel *dynamicHeaderLbl_197;
//    QSpinBox *dynamicHeaderSpBx_197;
//    QLabel *dynamicHeaderLbl_198;
//    QSpinBox *dynamicHeaderSpBx_198;
//    QLabel *dynamicHeaderLbl_199;
//    QSpinBox *dynamicHeaderSpBx_199;
//    QLabel *dynamicHeaderLbl_200;
//    QSpinBox *dynamicHeaderSpBx_200;
//    QLabel *dynamicHeaderLbl_201;
//    QSpinBox *dynamicHeaderSpBx_201;
//    QLabel *dynamicHeaderLbl_202;
//    QSpinBox *dynamicHeaderSpBx_202;
//    QLabel *dynamicHeaderLbl_203;
//    QSpinBox *dynamicHeaderSpBx_203;
//    QLabel *dynamicHeaderLbl_204;
//    QSpinBox *dynamicHeaderSpBx_204;
//    QLabel *dynamicHeaderLbl_205;
//    QSpinBox *dynamicHeaderSpBx_205;
//    QLabel *dynamicHeaderLbl_206;
//    QSpinBox *dynamicHeaderSpBx_206;
//    QLabel *dynamicHeaderLbl_207;
//    QSpinBox *dynamicHeaderSpBx_207;
//    QLabel *dynamicHeaderLbl_208;
//    QSpinBox *dynamicHeaderSpBx_208;
//    QLabel *dynamicHeaderLbl_209;
//    QSpinBox *dynamicHeaderSpBx_209;
//    QLabel *dynamicHeaderLbl_210;
//    QSpinBox *dynamicHeaderSpBx_210;
//    QLabel *dynamicHeaderLbl_211;
//    QSpinBox *dynamicHeaderSpBx_211;
//    QLabel *dynamicHeaderLbl_212;
//    QSpinBox *dynamicHeaderSpBx_212;
//    QLabel *dynamicHeaderLbl_213;
//    QSpinBox *dynamicHeaderSpBx_213;
//    QLabel *dynamicHeaderLbl_214;
//    QSpinBox *dynamicHeaderSpBx_214;
//    QLabel *dynamicHeaderLbl_215;
//    QSpinBox *dynamicHeaderSpBx_215;
//    QLabel *dynamicHeaderLbl_216;
//    QSpinBox *dynamicHeaderSpBx_216;
//    QLabel *dynamicHeaderLbl_217;
//    QSpinBox *dynamicHeaderSpBx_217;
//    QLabel *dynamicHeaderLbl_218;
//    QSpinBox *dynamicHeaderSpBx_218;
//    QLabel *dynamicHeaderLbl_219;
//    QSpinBox *dynamicHeaderSpBx_219;
//    QLabel *dynamicHeaderLbl_220;
//    QSpinBox *dynamicHeaderSpBx_220;
//    QLabel *dynamicHeaderLbl_221;
//    QSpinBox *dynamicHeaderSpBx_221;
//    QLabel *dynamicHeaderLbl_222;
//    QSpinBox *dynamicHeaderSpBx_222;
//    QLabel *dynamicHeaderLbl_223;
//    QSpinBox *dynamicHeaderSpBx_223;
//    QLabel *dynamicHeaderLbl_224;
//    QSpinBox *dynamicHeaderSpBx_224;
//    QLabel *dynamicHeaderLbl_225;
//    QSpinBox *dynamicHeaderSpBx_225;
//    QLabel *dynamicHeaderLbl_226;
//    QSpinBox *dynamicHeaderSpBx_226;
//    QLabel *dynamicHeaderLbl_227;
//    QSpinBox *dynamicHeaderSpBx_227;
//    QLabel *dynamicHeaderLbl_228;
//    QSpinBox *dynamicHeaderSpBx_228;
//    QLabel *dynamicHeaderLbl_229;
//    QSpinBox *dynamicHeaderSpBx_229;
//    QLabel *dynamicHeaderLbl_230;
//    QSpinBox *dynamicHeaderSpBx_230;
//    QLabel *dynamicHeaderLbl_231;
//    QSpinBox *dynamicHeaderSpBx_231;
//    QLabel *dynamicHeaderLbl_232;
//    QSpinBox *dynamicHeaderSpBx_232;
//    QLabel *dynamicHeaderLbl_233;
//    QSpinBox *dynamicHeaderSpBx_233;
//    QLabel *dynamicHeaderLbl_234;
//    QSpinBox *dynamicHeaderSpBx_234;
//    QLabel *dynamicHeaderLbl_235;
//    QSpinBox *dynamicHeaderSpBx_235;
//    QLabel *dynamicHeaderLbl_236;
//    QSpinBox *dynamicHeaderSpBx_236;
//    QLabel *dynamicHeaderLbl_237;
//    QSpinBox *dynamicHeaderSpBx_237;
//    QLabel *dynamicHeaderLbl_238;
//    QSpinBox *dynamicHeaderSpBx_238;
//    QLabel *dynamicHeaderLbl_239;
//    QSpinBox *dynamicHeaderSpBx_239;
//    QLabel *dynamicHeaderLbl_240;
//    QSpinBox *dynamicHeaderSpBx_240;
//    QLabel *dynamicHeaderLbl_241;
//    QSpinBox *dynamicHeaderSpBx_241;
//    QLabel *dynamicHeaderLbl_242;
//    QSpinBox *dynamicHeaderSpBx_242;
//    QLabel *dynamicHeaderLbl_243;
//    QSpinBox *dynamicHeaderSpBx_243;
//    QLabel *dynamicHeaderLbl_244;
//    QSpinBox *dynamicHeaderSpBx_244;
//    QLabel *dynamicHeaderLbl_245;
//    QSpinBox *dynamicHeaderSpBx_245;
//    QLabel *dynamicHeaderLbl_246;
//    QSpinBox *dynamicHeaderSpBx_246;
//    QLabel *dynamicHeaderLbl_247;
//    QSpinBox *dynamicHeaderSpBx_247;
//    QLabel *dynamicHeaderLbl_248;
//    QSpinBox *dynamicHeaderSpBx_248;
//    QLabel *dynamicHeaderLbl_249;
//    QSpinBox *dynamicHeaderSpBx_249;
//    QLabel *dynamicHeaderLbl_250;
//    QSpinBox *dynamicHeaderSpBx_250;
//    QLabel *dynamicHeaderLbl_251;
//    QSpinBox *dynamicHeaderSpBx_251;
//    QLabel *dynamicHeaderLbl_252;
//    QSpinBox *dynamicHeaderSpBx_252;
//    QLabel *dynamicHeaderLbl_253;
//    QSpinBox *dynamicHeaderSpBx_253;
//    QLabel *dynamicHeaderLbl_254;
//    QSpinBox *dynamicHeaderSpBx_254;
//    QLabel *dynamicHeaderLbl_255;
//    QSpinBox *dynamicHeaderSpBx_255;

    QLabel *dynamicBrickContentLbl_1;
    QSpinBox *dynamicBrickContentSpBx_1;
    QLabel *dynamicBrickMaskLbl_1;
    QSpinBox *dynamicBrickMaskSpBx_1;
    QLabel *dynamicBrickContentLbl_2;
    QSpinBox *dynamicBrickContentSpBx_2;
    QLabel *dynamicBrickMaskLbl_2;
    QSpinBox *dynamicBrickMaskSpBx_2;
    QLabel *dynamicBrickContentLbl_3;
    QSpinBox *dynamicBrickContentSpBx_3;
    QLabel *dynamicBrickMaskLbl_3;
    QSpinBox *dynamicBrickMaskSpBx_3;
    QLabel *dynamicBrickContentLbl_4;
    QSpinBox *dynamicBrickContentSpBx_4;
    QLabel *dynamicBrickMaskLbl_4;
    QSpinBox *dynamicBrickMaskSpBx_4;
    QLabel *dynamicBrickContentLbl_5;
    QSpinBox *dynamicBrickContentSpBx_5;
    QLabel *dynamicBrickMaskLbl_5;
    QSpinBox *dynamicBrickMaskSpBx_5;
    QLabel *dynamicBrickContentLbl_6;
    QSpinBox *dynamicBrickContentSpBx_6;
    QLabel *dynamicBrickMaskLbl_6;
    QSpinBox *dynamicBrickMaskSpBx_6;
    QLabel *dynamicBrickContentLbl_7;
    QSpinBox *dynamicBrickContentSpBx_7;
    QLabel *dynamicBrickMaskLbl_7;
    QSpinBox *dynamicBrickMaskSpBx_7;
    QLabel *dynamicBrickContentLbl_8;
    QSpinBox *dynamicBrickContentSpBx_8;
    QLabel *dynamicBrickMaskLbl_8;
    QSpinBox *dynamicBrickMaskSpBx_8;
    QLabel *dynamicBrickContentLbl_9;
    QSpinBox *dynamicBrickContentSpBx_9;
    QLabel *dynamicBrickMaskLbl_9;
    QSpinBox *dynamicBrickMaskSpBx_9;
    QLabel *dynamicBrickContentLbl_10;
    QSpinBox *dynamicBrickContentSpBx_10;
    QLabel *dynamicBrickMaskLbl_10;
    QSpinBox *dynamicBrickMaskSpBx_10;

//    QLabel *dynamicBrickContentLbl_11;
//    QSpinBox *dynamicBrickContentSpBx_11;
//    QLabel *dynamicBrickMaskLbl_11;
//    QSpinBox *dynamicBrickMaskSpBx_11;
//    QLabel *dynamicBrickContentLbl_12;
//    QSpinBox *dynamicBrickContentSpBx_12;
//    QLabel *dynamicBrickMaskLbl_12;
//    QSpinBox *dynamicBrickMaskSpBx_12;
//    QLabel *dynamicBrickContentLbl_13;
//    QSpinBox *dynamicBrickContentSpBx_13;
//    QLabel *dynamicBrickMaskLbl_13;
//    QSpinBox *dynamicBrickMaskSpBx_13;
//    QLabel *dynamicBrickContentLbl_14;
//    QSpinBox *dynamicBrickContentSpBx_14;
//    QLabel *dynamicBrickMaskLbl_14;
//    QSpinBox *dynamicBrickMaskSpBx_14;
//    QLabel *dynamicBrickContentLbl_15;
//    QSpinBox *dynamicBrickContentSpBx_15;
//    QLabel *dynamicBrickMaskLbl_15;
//    QSpinBox *dynamicBrickMaskSpBx_15;
//    QLabel *dynamicBrickContentLbl_16;
//    QSpinBox *dynamicBrickContentSpBx_16;
//    QLabel *dynamicBrickMaskLbl_16;
//    QSpinBox *dynamicBrickMaskSpBx_16;
//    QLabel *dynamicBrickContentLbl_17;
//    QSpinBox *dynamicBrickContentSpBx_17;
//    QLabel *dynamicBrickMaskLbl_17;
//    QSpinBox *dynamicBrickMaskSpBx_17;
//    QLabel *dynamicBrickContentLbl_18;
//    QSpinBox *dynamicBrickContentSpBx_18;
//    QLabel *dynamicBrickMaskLbl_18;
//    QSpinBox *dynamicBrickMaskSpBx_18;
//    QLabel *dynamicBrickContentLbl_19;
//    QSpinBox *dynamicBrickContentSpBx_19;
//    QLabel *dynamicBrickMaskLbl_19;
//    QSpinBox *dynamicBrickMaskSpBx_19;
//    QLabel *dynamicBrickContentLbl_20;
//    QSpinBox *dynamicBrickContentSpBx_20;
//    QLabel *dynamicBrickMaskLbl_20;
//    QSpinBox *dynamicBrickMaskSpBx_20;
//    QLabel *dynamicBrickContentLbl_21;
//    QSpinBox *dynamicBrickContentSpBx_21;
//    QLabel *dynamicBrickMaskLbl_21;
//    QSpinBox *dynamicBrickMaskSpBx_21;
//    QLabel *dynamicBrickContentLbl_22;
//    QSpinBox *dynamicBrickContentSpBx_22;
//    QLabel *dynamicBrickMaskLbl_22;
//    QSpinBox *dynamicBrickMaskSpBx_22;
//    QLabel *dynamicBrickContentLbl_23;
//    QSpinBox *dynamicBrickContentSpBx_23;
//    QLabel *dynamicBrickMaskLbl_23;
//    QSpinBox *dynamicBrickMaskSpBx_23;
//    QLabel *dynamicBrickContentLbl_24;
//    QSpinBox *dynamicBrickContentSpBx_24;
//    QLabel *dynamicBrickMaskLbl_24;
//    QSpinBox *dynamicBrickMaskSpBx_24;
//    QLabel *dynamicBrickContentLbl_25;
//    QSpinBox *dynamicBrickContentSpBx_25;
//    QLabel *dynamicBrickMaskLbl_25;
//    QSpinBox *dynamicBrickMaskSpBx_25;
//    QLabel *dynamicBrickContentLbl_26;
//    QSpinBox *dynamicBrickContentSpBx_26;
//    QLabel *dynamicBrickMaskLbl_26;
//    QSpinBox *dynamicBrickMaskSpBx_26;
//    QLabel *dynamicBrickContentLbl_27;
//    QSpinBox *dynamicBrickContentSpBx_27;
//    QLabel *dynamicBrickMaskLbl_27;
//    QSpinBox *dynamicBrickMaskSpBx_27;
//    QLabel *dynamicBrickContentLbl_28;
//    QSpinBox *dynamicBrickContentSpBx_28;
//    QLabel *dynamicBrickMaskLbl_28;
//    QSpinBox *dynamicBrickMaskSpBx_28;
//    QLabel *dynamicBrickContentLbl_29;
//    QSpinBox *dynamicBrickContentSpBx_29;
//    QLabel *dynamicBrickMaskLbl_29;
//    QSpinBox *dynamicBrickMaskSpBx_29;
//    QLabel *dynamicBrickContentLbl_30;
//    QSpinBox *dynamicBrickContentSpBx_30;
//    QLabel *dynamicBrickMaskLbl_30;
//    QSpinBox *dynamicBrickMaskSpBx_30;
//    QLabel *dynamicBrickContentLbl_31;
//    QSpinBox *dynamicBrickContentSpBx_31;
//    QLabel *dynamicBrickMaskLbl_31;
//    QSpinBox *dynamicBrickMaskSpBx_31;
//    QLabel *dynamicBrickContentLbl_32;
//    QSpinBox *dynamicBrickContentSpBx_32;
//    QLabel *dynamicBrickMaskLbl_32;
//    QSpinBox *dynamicBrickMaskSpBx_32;
//    QLabel *dynamicBrickContentLbl_33;
//    QSpinBox *dynamicBrickContentSpBx_33;
//    QLabel *dynamicBrickMaskLbl_33;
//    QSpinBox *dynamicBrickMaskSpBx_33;
//    QLabel *dynamicBrickContentLbl_34;
//    QSpinBox *dynamicBrickContentSpBx_34;
//    QLabel *dynamicBrickMaskLbl_34;
//    QSpinBox *dynamicBrickMaskSpBx_34;
//    QLabel *dynamicBrickContentLbl_35;
//    QSpinBox *dynamicBrickContentSpBx_35;
//    QLabel *dynamicBrickMaskLbl_35;
//    QSpinBox *dynamicBrickMaskSpBx_35;
//    QLabel *dynamicBrickContentLbl_36;
//    QSpinBox *dynamicBrickContentSpBx_36;
//    QLabel *dynamicBrickMaskLbl_36;
//    QSpinBox *dynamicBrickMaskSpBx_36;
//    QLabel *dynamicBrickContentLbl_37;
//    QSpinBox *dynamicBrickContentSpBx_37;
//    QLabel *dynamicBrickMaskLbl_37;
//    QSpinBox *dynamicBrickMaskSpBx_37;
//    QLabel *dynamicBrickContentLbl_38;
//    QSpinBox *dynamicBrickContentSpBx_38;
//    QLabel *dynamicBrickMaskLbl_38;
//    QSpinBox *dynamicBrickMaskSpBx_38;
//    QLabel *dynamicBrickContentLbl_39;
//    QSpinBox *dynamicBrickContentSpBx_39;
//    QLabel *dynamicBrickMaskLbl_39;
//    QSpinBox *dynamicBrickMaskSpBx_39;
//    QLabel *dynamicBrickContentLbl_40;
//    QSpinBox *dynamicBrickContentSpBx_40;
//    QLabel *dynamicBrickMaskLbl_40;
//    QSpinBox *dynamicBrickMaskSpBx_40;
//    QLabel *dynamicBrickContentLbl_41;
//    QSpinBox *dynamicBrickContentSpBx_41;
//    QLabel *dynamicBrickMaskLbl_41;
//    QSpinBox *dynamicBrickMaskSpBx_41;
//    QLabel *dynamicBrickContentLbl_42;
//    QSpinBox *dynamicBrickContentSpBx_42;
//    QLabel *dynamicBrickMaskLbl_42;
//    QSpinBox *dynamicBrickMaskSpBx_42;
//    QLabel *dynamicBrickContentLbl_43;
//    QSpinBox *dynamicBrickContentSpBx_43;
//    QLabel *dynamicBrickMaskLbl_43;
//    QSpinBox *dynamicBrickMaskSpBx_43;
//    QLabel *dynamicBrickContentLbl_44;
//    QSpinBox *dynamicBrickContentSpBx_44;
//    QLabel *dynamicBrickMaskLbl_44;
//    QSpinBox *dynamicBrickMaskSpBx_44;
//    QLabel *dynamicBrickContentLbl_45;
//    QSpinBox *dynamicBrickContentSpBx_45;
//    QLabel *dynamicBrickMaskLbl_45;
//    QSpinBox *dynamicBrickMaskSpBx_45;
//    QLabel *dynamicBrickContentLbl_46;
//    QSpinBox *dynamicBrickContentSpBx_46;
//    QLabel *dynamicBrickMaskLbl_46;
//    QSpinBox *dynamicBrickMaskSpBx_46;
//    QLabel *dynamicBrickContentLbl_47;
//    QSpinBox *dynamicBrickContentSpBx_47;
//    QLabel *dynamicBrickMaskLbl_47;
//    QSpinBox *dynamicBrickMaskSpBx_47;
//    QLabel *dynamicBrickContentLbl_48;
//    QSpinBox *dynamicBrickContentSpBx_48;
//    QLabel *dynamicBrickMaskLbl_48;
//    QSpinBox *dynamicBrickMaskSpBx_48;
//    QLabel *dynamicBrickContentLbl_49;
//    QSpinBox *dynamicBrickContentSpBx_49;
//    QLabel *dynamicBrickMaskLbl_49;
//    QSpinBox *dynamicBrickMaskSpBx_49;
//    QLabel *dynamicBrickContentLbl_50;
//    QSpinBox *dynamicBrickContentSpBx_50;
//    QLabel *dynamicBrickMaskLbl_50;
//    QSpinBox *dynamicBrickMaskSpBx_50;
//    QLabel *dynamicBrickContentLbl_51;
//    QSpinBox *dynamicBrickContentSpBx_51;
//    QLabel *dynamicBrickMaskLbl_51;
//    QSpinBox *dynamicBrickMaskSpBx_51;
//    QLabel *dynamicBrickContentLbl_52;
//    QSpinBox *dynamicBrickContentSpBx_52;
//    QLabel *dynamicBrickMaskLbl_52;
//    QSpinBox *dynamicBrickMaskSpBx_52;
//    QLabel *dynamicBrickContentLbl_53;
//    QSpinBox *dynamicBrickContentSpBx_53;
//    QLabel *dynamicBrickMaskLbl_53;
//    QSpinBox *dynamicBrickMaskSpBx_53;
//    QLabel *dynamicBrickContentLbl_54;
//    QSpinBox *dynamicBrickContentSpBx_54;
//    QLabel *dynamicBrickMaskLbl_54;
//    QSpinBox *dynamicBrickMaskSpBx_54;
//    QLabel *dynamicBrickContentLbl_55;
//    QSpinBox *dynamicBrickContentSpBx_55;
//    QLabel *dynamicBrickMaskLbl_55;
//    QSpinBox *dynamicBrickMaskSpBx_55;
//    QLabel *dynamicBrickContentLbl_56;
//    QSpinBox *dynamicBrickContentSpBx_56;
//    QLabel *dynamicBrickMaskLbl_56;
//    QSpinBox *dynamicBrickMaskSpBx_56;
//    QLabel *dynamicBrickContentLbl_57;
//    QSpinBox *dynamicBrickContentSpBx_57;
//    QLabel *dynamicBrickMaskLbl_57;
//    QSpinBox *dynamicBrickMaskSpBx_57;
//    QLabel *dynamicBrickContentLbl_58;
//    QSpinBox *dynamicBrickContentSpBx_58;
//    QLabel *dynamicBrickMaskLbl_58;
//    QSpinBox *dynamicBrickMaskSpBx_58;
//    QLabel *dynamicBrickContentLbl_59;
//    QSpinBox *dynamicBrickContentSpBx_59;
//    QLabel *dynamicBrickMaskLbl_59;
//    QSpinBox *dynamicBrickMaskSpBx_59;
//    QLabel *dynamicBrickContentLbl_60;
//    QSpinBox *dynamicBrickContentSpBx_60;
//    QLabel *dynamicBrickMaskLbl_60;
//    QSpinBox *dynamicBrickMaskSpBx_60;
//    QLabel *dynamicBrickContentLbl_61;
//    QSpinBox *dynamicBrickContentSpBx_61;
//    QLabel *dynamicBrickMaskLbl_61;
//    QSpinBox *dynamicBrickMaskSpBx_61;
//    QLabel *dynamicBrickContentLbl_62;
//    QSpinBox *dynamicBrickContentSpBx_62;
//    QLabel *dynamicBrickMaskLbl_62;
//    QSpinBox *dynamicBrickMaskSpBx_62;
//    QLabel *dynamicBrickContentLbl_63;
//    QSpinBox *dynamicBrickContentSpBx_63;
//    QLabel *dynamicBrickMaskLbl_63;
//    QSpinBox *dynamicBrickMaskSpBx_63;
//    QLabel *dynamicBrickContentLbl_64;
//    QSpinBox *dynamicBrickContentSpBx_64;
//    QLabel *dynamicBrickMaskLbl_64;
//    QSpinBox *dynamicBrickMaskSpBx_64;
//    QLabel *dynamicBrickContentLbl_65;
//    QSpinBox *dynamicBrickContentSpBx_65;
//    QLabel *dynamicBrickMaskLbl_65;
//    QSpinBox *dynamicBrickMaskSpBx_65;
//    QLabel *dynamicBrickContentLbl_66;
//    QSpinBox *dynamicBrickContentSpBx_66;
//    QLabel *dynamicBrickMaskLbl_66;
//    QSpinBox *dynamicBrickMaskSpBx_66;
//    QLabel *dynamicBrickContentLbl_67;
//    QSpinBox *dynamicBrickContentSpBx_67;
//    QLabel *dynamicBrickMaskLbl_67;
//    QSpinBox *dynamicBrickMaskSpBx_67;
//    QLabel *dynamicBrickContentLbl_68;
//    QSpinBox *dynamicBrickContentSpBx_68;
//    QLabel *dynamicBrickMaskLbl_68;
//    QSpinBox *dynamicBrickMaskSpBx_68;
//    QLabel *dynamicBrickContentLbl_69;
//    QSpinBox *dynamicBrickContentSpBx_69;
//    QLabel *dynamicBrickMaskLbl_69;
//    QSpinBox *dynamicBrickMaskSpBx_69;
//    QLabel *dynamicBrickContentLbl_70;
//    QSpinBox *dynamicBrickContentSpBx_70;
//    QLabel *dynamicBrickMaskLbl_70;
//    QSpinBox *dynamicBrickMaskSpBx_70;
//    QLabel *dynamicBrickContentLbl_71;
//    QSpinBox *dynamicBrickContentSpBx_71;
//    QLabel *dynamicBrickMaskLbl_71;
//    QSpinBox *dynamicBrickMaskSpBx_71;
//    QLabel *dynamicBrickContentLbl_72;
//    QSpinBox *dynamicBrickContentSpBx_72;
//    QLabel *dynamicBrickMaskLbl_72;
//    QSpinBox *dynamicBrickMaskSpBx_72;
//    QLabel *dynamicBrickContentLbl_73;
//    QSpinBox *dynamicBrickContentSpBx_73;
//    QLabel *dynamicBrickMaskLbl_73;
//    QSpinBox *dynamicBrickMaskSpBx_73;
//    QLabel *dynamicBrickContentLbl_74;
//    QSpinBox *dynamicBrickContentSpBx_74;
//    QLabel *dynamicBrickMaskLbl_74;
//    QSpinBox *dynamicBrickMaskSpBx_74;
//    QLabel *dynamicBrickContentLbl_75;
//    QSpinBox *dynamicBrickContentSpBx_75;
//    QLabel *dynamicBrickMaskLbl_75;
//    QSpinBox *dynamicBrickMaskSpBx_75;
//    QLabel *dynamicBrickContentLbl_76;
//    QSpinBox *dynamicBrickContentSpBx_76;
//    QLabel *dynamicBrickMaskLbl_76;
//    QSpinBox *dynamicBrickMaskSpBx_76;
//    QLabel *dynamicBrickContentLbl_77;
//    QSpinBox *dynamicBrickContentSpBx_77;
//    QLabel *dynamicBrickMaskLbl_77;
//    QSpinBox *dynamicBrickMaskSpBx_77;
//    QLabel *dynamicBrickContentLbl_78;
//    QSpinBox *dynamicBrickContentSpBx_78;
//    QLabel *dynamicBrickMaskLbl_78;
//    QSpinBox *dynamicBrickMaskSpBx_78;
//    QLabel *dynamicBrickContentLbl_79;
//    QSpinBox *dynamicBrickContentSpBx_79;
//    QLabel *dynamicBrickMaskLbl_79;
//    QSpinBox *dynamicBrickMaskSpBx_79;
//    QLabel *dynamicBrickContentLbl_80;
//    QSpinBox *dynamicBrickContentSpBx_80;
//    QLabel *dynamicBrickMaskLbl_80;
//    QSpinBox *dynamicBrickMaskSpBx_80;
//    QLabel *dynamicBrickContentLbl_81;
//    QSpinBox *dynamicBrickContentSpBx_81;
//    QLabel *dynamicBrickMaskLbl_81;
//    QSpinBox *dynamicBrickMaskSpBx_81;
//    QLabel *dynamicBrickContentLbl_82;
//    QSpinBox *dynamicBrickContentSpBx_82;
//    QLabel *dynamicBrickMaskLbl_82;
//    QSpinBox *dynamicBrickMaskSpBx_82;
//    QLabel *dynamicBrickContentLbl_83;
//    QSpinBox *dynamicBrickContentSpBx_83;
//    QLabel *dynamicBrickMaskLbl_83;
//    QSpinBox *dynamicBrickMaskSpBx_83;
//    QLabel *dynamicBrickContentLbl_84;
//    QSpinBox *dynamicBrickContentSpBx_84;
//    QLabel *dynamicBrickMaskLbl_84;
//    QSpinBox *dynamicBrickMaskSpBx_84;
//    QLabel *dynamicBrickContentLbl_85;
//    QSpinBox *dynamicBrickContentSpBx_85;
//    QLabel *dynamicBrickMaskLbl_85;
//    QSpinBox *dynamicBrickMaskSpBx_85;
//    QLabel *dynamicBrickContentLbl_86;
//    QSpinBox *dynamicBrickContentSpBx_86;
//    QLabel *dynamicBrickMaskLbl_86;
//    QSpinBox *dynamicBrickMaskSpBx_86;
//    QLabel *dynamicBrickContentLbl_87;
//    QSpinBox *dynamicBrickContentSpBx_87;
//    QLabel *dynamicBrickMaskLbl_87;
//    QSpinBox *dynamicBrickMaskSpBx_87;
//    QLabel *dynamicBrickContentLbl_88;
//    QSpinBox *dynamicBrickContentSpBx_88;
//    QLabel *dynamicBrickMaskLbl_88;
//    QSpinBox *dynamicBrickMaskSpBx_88;
//    QLabel *dynamicBrickContentLbl_89;
//    QSpinBox *dynamicBrickContentSpBx_89;
//    QLabel *dynamicBrickMaskLbl_89;
//    QSpinBox *dynamicBrickMaskSpBx_89;
//    QLabel *dynamicBrickContentLbl_90;
//    QSpinBox *dynamicBrickContentSpBx_90;
//    QLabel *dynamicBrickMaskLbl_90;
//    QSpinBox *dynamicBrickMaskSpBx_90;
//    QLabel *dynamicBrickContentLbl_91;
//    QSpinBox *dynamicBrickContentSpBx_91;
//    QLabel *dynamicBrickMaskLbl_91;
//    QSpinBox *dynamicBrickMaskSpBx_91;
//    QLabel *dynamicBrickContentLbl_92;
//    QSpinBox *dynamicBrickContentSpBx_92;
//    QLabel *dynamicBrickMaskLbl_92;
//    QSpinBox *dynamicBrickMaskSpBx_92;
//    QLabel *dynamicBrickContentLbl_93;
//    QSpinBox *dynamicBrickContentSpBx_93;
//    QLabel *dynamicBrickMaskLbl_93;
//    QSpinBox *dynamicBrickMaskSpBx_93;
//    QLabel *dynamicBrickContentLbl_94;
//    QSpinBox *dynamicBrickContentSpBx_94;
//    QLabel *dynamicBrickMaskLbl_94;
//    QSpinBox *dynamicBrickMaskSpBx_94;
//    QLabel *dynamicBrickContentLbl_95;
//    QSpinBox *dynamicBrickContentSpBx_95;
//    QLabel *dynamicBrickMaskLbl_95;
//    QSpinBox *dynamicBrickMaskSpBx_95;
//    QLabel *dynamicBrickContentLbl_96;
//    QSpinBox *dynamicBrickContentSpBx_96;
//    QLabel *dynamicBrickMaskLbl_96;
//    QSpinBox *dynamicBrickMaskSpBx_96;
//    QLabel *dynamicBrickContentLbl_97;
//    QSpinBox *dynamicBrickContentSpBx_97;
//    QLabel *dynamicBrickMaskLbl_97;
//    QSpinBox *dynamicBrickMaskSpBx_97;
//    QLabel *dynamicBrickContentLbl_98;
//    QSpinBox *dynamicBrickContentSpBx_98;
//    QLabel *dynamicBrickMaskLbl_98;
//    QSpinBox *dynamicBrickMaskSpBx_98;
//    QLabel *dynamicBrickContentLbl_99;
//    QSpinBox *dynamicBrickContentSpBx_99;
//    QLabel *dynamicBrickMaskLbl_99;
//    QSpinBox *dynamicBrickMaskSpBx_99;
//    QLabel *dynamicBrickContentLbl_100;
//    QSpinBox *dynamicBrickContentSpBx_100;
//    QLabel *dynamicBrickMaskLbl_100;
//    QSpinBox *dynamicBrickMaskSpBx_100;
//    QLabel *dynamicBrickContentLbl_101;
//    QSpinBox *dynamicBrickContentSpBx_101;
//    QLabel *dynamicBrickMaskLbl_101;
//    QSpinBox *dynamicBrickMaskSpBx_101;
//    QLabel *dynamicBrickContentLbl_102;
//    QSpinBox *dynamicBrickContentSpBx_102;
//    QLabel *dynamicBrickMaskLbl_102;
//    QSpinBox *dynamicBrickMaskSpBx_102;
//    QLabel *dynamicBrickContentLbl_103;
//    QSpinBox *dynamicBrickContentSpBx_103;
//    QLabel *dynamicBrickMaskLbl_103;
//    QSpinBox *dynamicBrickMaskSpBx_103;
//    QLabel *dynamicBrickContentLbl_104;
//    QSpinBox *dynamicBrickContentSpBx_104;
//    QLabel *dynamicBrickMaskLbl_104;
//    QSpinBox *dynamicBrickMaskSpBx_104;
//    QLabel *dynamicBrickContentLbl_105;
//    QSpinBox *dynamicBrickContentSpBx_105;
//    QLabel *dynamicBrickMaskLbl_105;
//    QSpinBox *dynamicBrickMaskSpBx_105;
//    QLabel *dynamicBrickContentLbl_106;
//    QSpinBox *dynamicBrickContentSpBx_106;
//    QLabel *dynamicBrickMaskLbl_106;
//    QSpinBox *dynamicBrickMaskSpBx_106;
//    QLabel *dynamicBrickContentLbl_107;
//    QSpinBox *dynamicBrickContentSpBx_107;
//    QLabel *dynamicBrickMaskLbl_107;
//    QSpinBox *dynamicBrickMaskSpBx_107;
//    QLabel *dynamicBrickContentLbl_108;
//    QSpinBox *dynamicBrickContentSpBx_108;
//    QLabel *dynamicBrickMaskLbl_108;
//    QSpinBox *dynamicBrickMaskSpBx_108;
//    QLabel *dynamicBrickContentLbl_109;
//    QSpinBox *dynamicBrickContentSpBx_109;
//    QLabel *dynamicBrickMaskLbl_109;
//    QSpinBox *dynamicBrickMaskSpBx_109;
//    QLabel *dynamicBrickContentLbl_110;
//    QSpinBox *dynamicBrickContentSpBx_110;
//    QLabel *dynamicBrickMaskLbl_110;
//    QSpinBox *dynamicBrickMaskSpBx_110;
//    QLabel *dynamicBrickContentLbl_111;
//    QSpinBox *dynamicBrickContentSpBx_111;
//    QLabel *dynamicBrickMaskLbl_111;
//    QSpinBox *dynamicBrickMaskSpBx_111;
//    QLabel *dynamicBrickContentLbl_112;
//    QSpinBox *dynamicBrickContentSpBx_112;
//    QLabel *dynamicBrickMaskLbl_112;
//    QSpinBox *dynamicBrickMaskSpBx_112;
//    QLabel *dynamicBrickContentLbl_113;
//    QSpinBox *dynamicBrickContentSpBx_113;
//    QLabel *dynamicBrickMaskLbl_113;
//    QSpinBox *dynamicBrickMaskSpBx_113;
//    QLabel *dynamicBrickContentLbl_114;
//    QSpinBox *dynamicBrickContentSpBx_114;
//    QLabel *dynamicBrickMaskLbl_114;
//    QSpinBox *dynamicBrickMaskSpBx_114;
//    QLabel *dynamicBrickContentLbl_115;
//    QSpinBox *dynamicBrickContentSpBx_115;
//    QLabel *dynamicBrickMaskLbl_115;
//    QSpinBox *dynamicBrickMaskSpBx_115;
//    QLabel *dynamicBrickContentLbl_116;
//    QSpinBox *dynamicBrickContentSpBx_116;
//    QLabel *dynamicBrickMaskLbl_116;
//    QSpinBox *dynamicBrickMaskSpBx_116;
//    QLabel *dynamicBrickContentLbl_117;
//    QSpinBox *dynamicBrickContentSpBx_117;
//    QLabel *dynamicBrickMaskLbl_117;
//    QSpinBox *dynamicBrickMaskSpBx_117;
//    QLabel *dynamicBrickContentLbl_118;
//    QSpinBox *dynamicBrickContentSpBx_118;
//    QLabel *dynamicBrickMaskLbl_118;
//    QSpinBox *dynamicBrickMaskSpBx_118;
//    QLabel *dynamicBrickContentLbl_119;
//    QSpinBox *dynamicBrickContentSpBx_119;
//    QLabel *dynamicBrickMaskLbl_119;
//    QSpinBox *dynamicBrickMaskSpBx_119;
//    QLabel *dynamicBrickContentLbl_120;
//    QSpinBox *dynamicBrickContentSpBx_120;
//    QLabel *dynamicBrickMaskLbl_120;
//    QSpinBox *dynamicBrickMaskSpBx_120;
//    QLabel *dynamicBrickContentLbl_121;
//    QSpinBox *dynamicBrickContentSpBx_121;
//    QLabel *dynamicBrickMaskLbl_121;
//    QSpinBox *dynamicBrickMaskSpBx_121;
//    QLabel *dynamicBrickContentLbl_122;
//    QSpinBox *dynamicBrickContentSpBx_122;
//    QLabel *dynamicBrickMaskLbl_122;
//    QSpinBox *dynamicBrickMaskSpBx_122;
//    QLabel *dynamicBrickContentLbl_123;
//    QSpinBox *dynamicBrickContentSpBx_123;
//    QLabel *dynamicBrickMaskLbl_123;
//    QSpinBox *dynamicBrickMaskSpBx_123;
//    QLabel *dynamicBrickContentLbl_124;
//    QSpinBox *dynamicBrickContentSpBx_124;
//    QLabel *dynamicBrickMaskLbl_124;
//    QSpinBox *dynamicBrickMaskSpBx_124;
//    QLabel *dynamicBrickContentLbl_125;
//    QSpinBox *dynamicBrickContentSpBx_125;
//    QLabel *dynamicBrickMaskLbl_125;
//    QSpinBox *dynamicBrickMaskSpBx_125;
//    QLabel *dynamicBrickContentLbl_126;
//    QSpinBox *dynamicBrickContentSpBx_126;
//    QLabel *dynamicBrickMaskLbl_126;
//    QSpinBox *dynamicBrickMaskSpBx_126;
//    QLabel *dynamicBrickContentLbl_127;
//    QSpinBox *dynamicBrickContentSpBx_127;
//    QLabel *dynamicBrickMaskLbl_127;
//    QSpinBox *dynamicBrickMaskSpBx_127;
//    QLabel *dynamicBrickContentLbl_128;
//    QSpinBox *dynamicBrickContentSpBx_128;
//    QLabel *dynamicBrickMaskLbl_128;
//    QSpinBox *dynamicBrickMaskSpBx_128;
//    QLabel *dynamicBrickContentLbl_129;
//    QSpinBox *dynamicBrickContentSpBx_129;
//    QLabel *dynamicBrickMaskLbl_129;
//    QSpinBox *dynamicBrickMaskSpBx_129;
//    QLabel *dynamicBrickContentLbl_130;
//    QSpinBox *dynamicBrickContentSpBx_130;
//    QLabel *dynamicBrickMaskLbl_130;
//    QSpinBox *dynamicBrickMaskSpBx_130;
//    QLabel *dynamicBrickContentLbl_131;
//    QSpinBox *dynamicBrickContentSpBx_131;
//    QLabel *dynamicBrickMaskLbl_131;
//    QSpinBox *dynamicBrickMaskSpBx_131;
//    QLabel *dynamicBrickContentLbl_132;
//    QSpinBox *dynamicBrickContentSpBx_132;
//    QLabel *dynamicBrickMaskLbl_132;
//    QSpinBox *dynamicBrickMaskSpBx_132;
//    QLabel *dynamicBrickContentLbl_133;
//    QSpinBox *dynamicBrickContentSpBx_133;
//    QLabel *dynamicBrickMaskLbl_133;
//    QSpinBox *dynamicBrickMaskSpBx_133;
//    QLabel *dynamicBrickContentLbl_134;
//    QSpinBox *dynamicBrickContentSpBx_134;
//    QLabel *dynamicBrickMaskLbl_134;
//    QSpinBox *dynamicBrickMaskSpBx_134;
//    QLabel *dynamicBrickContentLbl_135;
//    QSpinBox *dynamicBrickContentSpBx_135;
//    QLabel *dynamicBrickMaskLbl_135;
//    QSpinBox *dynamicBrickMaskSpBx_135;
//    QLabel *dynamicBrickContentLbl_136;
//    QSpinBox *dynamicBrickContentSpBx_136;
//    QLabel *dynamicBrickMaskLbl_136;
//    QSpinBox *dynamicBrickMaskSpBx_136;
//    QLabel *dynamicBrickContentLbl_137;
//    QSpinBox *dynamicBrickContentSpBx_137;
//    QLabel *dynamicBrickMaskLbl_137;
//    QSpinBox *dynamicBrickMaskSpBx_137;
//    QLabel *dynamicBrickContentLbl_138;
//    QSpinBox *dynamicBrickContentSpBx_138;
//    QLabel *dynamicBrickMaskLbl_138;
//    QSpinBox *dynamicBrickMaskSpBx_138;
//    QLabel *dynamicBrickContentLbl_139;
//    QSpinBox *dynamicBrickContentSpBx_139;
//    QLabel *dynamicBrickMaskLbl_139;
//    QSpinBox *dynamicBrickMaskSpBx_139;
//    QLabel *dynamicBrickContentLbl_140;
//    QSpinBox *dynamicBrickContentSpBx_140;
//    QLabel *dynamicBrickMaskLbl_140;
//    QSpinBox *dynamicBrickMaskSpBx_140;
//    QLabel *dynamicBrickContentLbl_141;
//    QSpinBox *dynamicBrickContentSpBx_141;
//    QLabel *dynamicBrickMaskLbl_141;
//    QSpinBox *dynamicBrickMaskSpBx_141;
//    QLabel *dynamicBrickContentLbl_142;
//    QSpinBox *dynamicBrickContentSpBx_142;
//    QLabel *dynamicBrickMaskLbl_142;
//    QSpinBox *dynamicBrickMaskSpBx_142;
//    QLabel *dynamicBrickContentLbl_143;
//    QSpinBox *dynamicBrickContentSpBx_143;
//    QLabel *dynamicBrickMaskLbl_143;
//    QSpinBox *dynamicBrickMaskSpBx_143;
//    QLabel *dynamicBrickContentLbl_144;
//    QSpinBox *dynamicBrickContentSpBx_144;
//    QLabel *dynamicBrickMaskLbl_144;
//    QSpinBox *dynamicBrickMaskSpBx_144;
//    QLabel *dynamicBrickContentLbl_145;
//    QSpinBox *dynamicBrickContentSpBx_145;
//    QLabel *dynamicBrickMaskLbl_145;
//    QSpinBox *dynamicBrickMaskSpBx_145;
//    QLabel *dynamicBrickContentLbl_146;
//    QSpinBox *dynamicBrickContentSpBx_146;
//    QLabel *dynamicBrickMaskLbl_146;
//    QSpinBox *dynamicBrickMaskSpBx_146;
//    QLabel *dynamicBrickContentLbl_147;
//    QSpinBox *dynamicBrickContentSpBx_147;
//    QLabel *dynamicBrickMaskLbl_147;
//    QSpinBox *dynamicBrickMaskSpBx_147;
//    QLabel *dynamicBrickContentLbl_148;
//    QSpinBox *dynamicBrickContentSpBx_148;
//    QLabel *dynamicBrickMaskLbl_148;
//    QSpinBox *dynamicBrickMaskSpBx_148;
//    QLabel *dynamicBrickContentLbl_149;
//    QSpinBox *dynamicBrickContentSpBx_149;
//    QLabel *dynamicBrickMaskLbl_149;
//    QSpinBox *dynamicBrickMaskSpBx_149;
//    QLabel *dynamicBrickContentLbl_150;
//    QSpinBox *dynamicBrickContentSpBx_150;
//    QLabel *dynamicBrickMaskLbl_150;
//    QSpinBox *dynamicBrickMaskSpBx_150;
//    QLabel *dynamicBrickContentLbl_151;
//    QSpinBox *dynamicBrickContentSpBx_151;
//    QLabel *dynamicBrickMaskLbl_151;
//    QSpinBox *dynamicBrickMaskSpBx_151;
//    QLabel *dynamicBrickContentLbl_152;
//    QSpinBox *dynamicBrickContentSpBx_152;
//    QLabel *dynamicBrickMaskLbl_152;
//    QSpinBox *dynamicBrickMaskSpBx_152;
//    QLabel *dynamicBrickContentLbl_153;
//    QSpinBox *dynamicBrickContentSpBx_153;
//    QLabel *dynamicBrickMaskLbl_153;
//    QSpinBox *dynamicBrickMaskSpBx_153;
//    QLabel *dynamicBrickContentLbl_154;
//    QSpinBox *dynamicBrickContentSpBx_154;
//    QLabel *dynamicBrickMaskLbl_154;
//    QSpinBox *dynamicBrickMaskSpBx_154;
//    QLabel *dynamicBrickContentLbl_155;
//    QSpinBox *dynamicBrickContentSpBx_155;
//    QLabel *dynamicBrickMaskLbl_155;
//    QSpinBox *dynamicBrickMaskSpBx_155;
//    QLabel *dynamicBrickContentLbl_156;
//    QSpinBox *dynamicBrickContentSpBx_156;
//    QLabel *dynamicBrickMaskLbl_156;
//    QSpinBox *dynamicBrickMaskSpBx_156;
//    QLabel *dynamicBrickContentLbl_157;
//    QSpinBox *dynamicBrickContentSpBx_157;
//    QLabel *dynamicBrickMaskLbl_157;
//    QSpinBox *dynamicBrickMaskSpBx_157;
//    QLabel *dynamicBrickContentLbl_158;
//    QSpinBox *dynamicBrickContentSpBx_158;
//    QLabel *dynamicBrickMaskLbl_158;
//    QSpinBox *dynamicBrickMaskSpBx_158;
//    QLabel *dynamicBrickContentLbl_159;
//    QSpinBox *dynamicBrickContentSpBx_159;
//    QLabel *dynamicBrickMaskLbl_159;
//    QSpinBox *dynamicBrickMaskSpBx_159;
//    QLabel *dynamicBrickContentLbl_160;
//    QSpinBox *dynamicBrickContentSpBx_160;
//    QLabel *dynamicBrickMaskLbl_160;
//    QSpinBox *dynamicBrickMaskSpBx_160;
//    QLabel *dynamicBrickContentLbl_161;
//    QSpinBox *dynamicBrickContentSpBx_161;
//    QLabel *dynamicBrickMaskLbl_161;
//    QSpinBox *dynamicBrickMaskSpBx_161;
//    QLabel *dynamicBrickContentLbl_162;
//    QSpinBox *dynamicBrickContentSpBx_162;
//    QLabel *dynamicBrickMaskLbl_162;
//    QSpinBox *dynamicBrickMaskSpBx_162;
//    QLabel *dynamicBrickContentLbl_163;
//    QSpinBox *dynamicBrickContentSpBx_163;
//    QLabel *dynamicBrickMaskLbl_163;
//    QSpinBox *dynamicBrickMaskSpBx_163;
//    QLabel *dynamicBrickContentLbl_164;
//    QSpinBox *dynamicBrickContentSpBx_164;
//    QLabel *dynamicBrickMaskLbl_164;
//    QSpinBox *dynamicBrickMaskSpBx_164;
//    QLabel *dynamicBrickContentLbl_165;
//    QSpinBox *dynamicBrickContentSpBx_165;
//    QLabel *dynamicBrickMaskLbl_165;
//    QSpinBox *dynamicBrickMaskSpBx_165;
//    QLabel *dynamicBrickContentLbl_166;
//    QSpinBox *dynamicBrickContentSpBx_166;
//    QLabel *dynamicBrickMaskLbl_166;
//    QSpinBox *dynamicBrickMaskSpBx_166;
//    QLabel *dynamicBrickContentLbl_167;
//    QSpinBox *dynamicBrickContentSpBx_167;
//    QLabel *dynamicBrickMaskLbl_167;
//    QSpinBox *dynamicBrickMaskSpBx_167;
//    QLabel *dynamicBrickContentLbl_168;
//    QSpinBox *dynamicBrickContentSpBx_168;
//    QLabel *dynamicBrickMaskLbl_168;
//    QSpinBox *dynamicBrickMaskSpBx_168;
//    QLabel *dynamicBrickContentLbl_169;
//    QSpinBox *dynamicBrickContentSpBx_169;
//    QLabel *dynamicBrickMaskLbl_169;
//    QSpinBox *dynamicBrickMaskSpBx_169;
//    QLabel *dynamicBrickContentLbl_170;
//    QSpinBox *dynamicBrickContentSpBx_170;
//    QLabel *dynamicBrickMaskLbl_170;
//    QSpinBox *dynamicBrickMaskSpBx_170;
//    QLabel *dynamicBrickContentLbl_171;
//    QSpinBox *dynamicBrickContentSpBx_171;
//    QLabel *dynamicBrickMaskLbl_171;
//    QSpinBox *dynamicBrickMaskSpBx_171;
//    QLabel *dynamicBrickContentLbl_172;
//    QSpinBox *dynamicBrickContentSpBx_172;
//    QLabel *dynamicBrickMaskLbl_172;
//    QSpinBox *dynamicBrickMaskSpBx_172;
//    QLabel *dynamicBrickContentLbl_173;
//    QSpinBox *dynamicBrickContentSpBx_173;
//    QLabel *dynamicBrickMaskLbl_173;
//    QSpinBox *dynamicBrickMaskSpBx_173;
//    QLabel *dynamicBrickContentLbl_174;
//    QSpinBox *dynamicBrickContentSpBx_174;
//    QLabel *dynamicBrickMaskLbl_174;
//    QSpinBox *dynamicBrickMaskSpBx_174;
//    QLabel *dynamicBrickContentLbl_175;
//    QSpinBox *dynamicBrickContentSpBx_175;
//    QLabel *dynamicBrickMaskLbl_175;
//    QSpinBox *dynamicBrickMaskSpBx_175;
//    QLabel *dynamicBrickContentLbl_176;
//    QSpinBox *dynamicBrickContentSpBx_176;
//    QLabel *dynamicBrickMaskLbl_176;
//    QSpinBox *dynamicBrickMaskSpBx_176;
//    QLabel *dynamicBrickContentLbl_177;
//    QSpinBox *dynamicBrickContentSpBx_177;
//    QLabel *dynamicBrickMaskLbl_177;
//    QSpinBox *dynamicBrickMaskSpBx_177;
//    QLabel *dynamicBrickContentLbl_178;
//    QSpinBox *dynamicBrickContentSpBx_178;
//    QLabel *dynamicBrickMaskLbl_178;
//    QSpinBox *dynamicBrickMaskSpBx_178;
//    QLabel *dynamicBrickContentLbl_179;
//    QSpinBox *dynamicBrickContentSpBx_179;
//    QLabel *dynamicBrickMaskLbl_179;
//    QSpinBox *dynamicBrickMaskSpBx_179;
//    QLabel *dynamicBrickContentLbl_180;
//    QSpinBox *dynamicBrickContentSpBx_180;
//    QLabel *dynamicBrickMaskLbl_180;
//    QSpinBox *dynamicBrickMaskSpBx_180;
//    QLabel *dynamicBrickContentLbl_181;
//    QSpinBox *dynamicBrickContentSpBx_181;
//    QLabel *dynamicBrickMaskLbl_181;
//    QSpinBox *dynamicBrickMaskSpBx_181;
//    QLabel *dynamicBrickContentLbl_182;
//    QSpinBox *dynamicBrickContentSpBx_182;
//    QLabel *dynamicBrickMaskLbl_182;
//    QSpinBox *dynamicBrickMaskSpBx_182;
//    QLabel *dynamicBrickContentLbl_183;
//    QSpinBox *dynamicBrickContentSpBx_183;
//    QLabel *dynamicBrickMaskLbl_183;
//    QSpinBox *dynamicBrickMaskSpBx_183;
//    QLabel *dynamicBrickContentLbl_184;
//    QSpinBox *dynamicBrickContentSpBx_184;
//    QLabel *dynamicBrickMaskLbl_184;
//    QSpinBox *dynamicBrickMaskSpBx_184;
//    QLabel *dynamicBrickContentLbl_185;
//    QSpinBox *dynamicBrickContentSpBx_185;
//    QLabel *dynamicBrickMaskLbl_185;
//    QSpinBox *dynamicBrickMaskSpBx_185;
//    QLabel *dynamicBrickContentLbl_186;
//    QSpinBox *dynamicBrickContentSpBx_186;
//    QLabel *dynamicBrickMaskLbl_186;
//    QSpinBox *dynamicBrickMaskSpBx_186;
//    QLabel *dynamicBrickContentLbl_187;
//    QSpinBox *dynamicBrickContentSpBx_187;
//    QLabel *dynamicBrickMaskLbl_187;
//    QSpinBox *dynamicBrickMaskSpBx_187;
//    QLabel *dynamicBrickContentLbl_188;
//    QSpinBox *dynamicBrickContentSpBx_188;
//    QLabel *dynamicBrickMaskLbl_188;
//    QSpinBox *dynamicBrickMaskSpBx_188;
//    QLabel *dynamicBrickContentLbl_189;
//    QSpinBox *dynamicBrickContentSpBx_189;
//    QLabel *dynamicBrickMaskLbl_189;
//    QSpinBox *dynamicBrickMaskSpBx_189;
//    QLabel *dynamicBrickContentLbl_190;
//    QSpinBox *dynamicBrickContentSpBx_190;
//    QLabel *dynamicBrickMaskLbl_190;
//    QSpinBox *dynamicBrickMaskSpBx_190;
//    QLabel *dynamicBrickContentLbl_191;
//    QSpinBox *dynamicBrickContentSpBx_191;
//    QLabel *dynamicBrickMaskLbl_191;
//    QSpinBox *dynamicBrickMaskSpBx_191;
//    QLabel *dynamicBrickContentLbl_192;
//    QSpinBox *dynamicBrickContentSpBx_192;
//    QLabel *dynamicBrickMaskLbl_192;
//    QSpinBox *dynamicBrickMaskSpBx_192;
//    QLabel *dynamicBrickContentLbl_193;
//    QSpinBox *dynamicBrickContentSpBx_193;
//    QLabel *dynamicBrickMaskLbl_193;
//    QSpinBox *dynamicBrickMaskSpBx_193;
//    QLabel *dynamicBrickContentLbl_194;
//    QSpinBox *dynamicBrickContentSpBx_194;
//    QLabel *dynamicBrickMaskLbl_194;
//    QSpinBox *dynamicBrickMaskSpBx_194;
//    QLabel *dynamicBrickContentLbl_195;
//    QSpinBox *dynamicBrickContentSpBx_195;
//    QLabel *dynamicBrickMaskLbl_195;
//    QSpinBox *dynamicBrickMaskSpBx_195;
//    QLabel *dynamicBrickContentLbl_196;
//    QSpinBox *dynamicBrickContentSpBx_196;
//    QLabel *dynamicBrickMaskLbl_196;
//    QSpinBox *dynamicBrickMaskSpBx_196;
//    QLabel *dynamicBrickContentLbl_197;
//    QSpinBox *dynamicBrickContentSpBx_197;
//    QLabel *dynamicBrickMaskLbl_197;
//    QSpinBox *dynamicBrickMaskSpBx_197;
//    QLabel *dynamicBrickContentLbl_198;
//    QSpinBox *dynamicBrickContentSpBx_198;
//    QLabel *dynamicBrickMaskLbl_198;
//    QSpinBox *dynamicBrickMaskSpBx_198;
//    QLabel *dynamicBrickContentLbl_199;
//    QSpinBox *dynamicBrickContentSpBx_199;
//    QLabel *dynamicBrickMaskLbl_199;
//    QSpinBox *dynamicBrickMaskSpBx_199;
//    QLabel *dynamicBrickContentLbl_200;
//    QSpinBox *dynamicBrickContentSpBx_200;
//    QLabel *dynamicBrickMaskLbl_200;
//    QSpinBox *dynamicBrickMaskSpBx_200;
//    QLabel *dynamicBrickContentLbl_201;
//    QSpinBox *dynamicBrickContentSpBx_201;
//    QLabel *dynamicBrickMaskLbl_201;
//    QSpinBox *dynamicBrickMaskSpBx_201;
//    QLabel *dynamicBrickContentLbl_202;
//    QSpinBox *dynamicBrickContentSpBx_202;
//    QLabel *dynamicBrickMaskLbl_202;
//    QSpinBox *dynamicBrickMaskSpBx_202;
//    QLabel *dynamicBrickContentLbl_203;
//    QSpinBox *dynamicBrickContentSpBx_203;
//    QLabel *dynamicBrickMaskLbl_203;
//    QSpinBox *dynamicBrickMaskSpBx_203;
//    QLabel *dynamicBrickContentLbl_204;
//    QSpinBox *dynamicBrickContentSpBx_204;
//    QLabel *dynamicBrickMaskLbl_204;
//    QSpinBox *dynamicBrickMaskSpBx_204;
//    QLabel *dynamicBrickContentLbl_205;
//    QSpinBox *dynamicBrickContentSpBx_205;
//    QLabel *dynamicBrickMaskLbl_205;
//    QSpinBox *dynamicBrickMaskSpBx_205;
//    QLabel *dynamicBrickContentLbl_206;
//    QSpinBox *dynamicBrickContentSpBx_206;
//    QLabel *dynamicBrickMaskLbl_206;
//    QSpinBox *dynamicBrickMaskSpBx_206;
//    QLabel *dynamicBrickContentLbl_207;
//    QSpinBox *dynamicBrickContentSpBx_207;
//    QLabel *dynamicBrickMaskLbl_207;
//    QSpinBox *dynamicBrickMaskSpBx_207;
//    QLabel *dynamicBrickContentLbl_208;
//    QSpinBox *dynamicBrickContentSpBx_208;
//    QLabel *dynamicBrickMaskLbl_208;
//    QSpinBox *dynamicBrickMaskSpBx_208;
//    QLabel *dynamicBrickContentLbl_209;
//    QSpinBox *dynamicBrickContentSpBx_209;
//    QLabel *dynamicBrickMaskLbl_209;
//    QSpinBox *dynamicBrickMaskSpBx_209;
//    QLabel *dynamicBrickContentLbl_210;
//    QSpinBox *dynamicBrickContentSpBx_210;
//    QLabel *dynamicBrickMaskLbl_210;
//    QSpinBox *dynamicBrickMaskSpBx_210;
//    QLabel *dynamicBrickContentLbl_211;
//    QSpinBox *dynamicBrickContentSpBx_211;
//    QLabel *dynamicBrickMaskLbl_211;
//    QSpinBox *dynamicBrickMaskSpBx_211;
//    QLabel *dynamicBrickContentLbl_212;
//    QSpinBox *dynamicBrickContentSpBx_212;
//    QLabel *dynamicBrickMaskLbl_212;
//    QSpinBox *dynamicBrickMaskSpBx_212;
//    QLabel *dynamicBrickContentLbl_213;
//    QSpinBox *dynamicBrickContentSpBx_213;
//    QLabel *dynamicBrickMaskLbl_213;
//    QSpinBox *dynamicBrickMaskSpBx_213;
//    QLabel *dynamicBrickContentLbl_214;
//    QSpinBox *dynamicBrickContentSpBx_214;
//    QLabel *dynamicBrickMaskLbl_214;
//    QSpinBox *dynamicBrickMaskSpBx_214;
//    QLabel *dynamicBrickContentLbl_215;
//    QSpinBox *dynamicBrickContentSpBx_215;
//    QLabel *dynamicBrickMaskLbl_215;
//    QSpinBox *dynamicBrickMaskSpBx_215;
//    QLabel *dynamicBrickContentLbl_216;
//    QSpinBox *dynamicBrickContentSpBx_216;
//    QLabel *dynamicBrickMaskLbl_216;
//    QSpinBox *dynamicBrickMaskSpBx_216;
//    QLabel *dynamicBrickContentLbl_217;
//    QSpinBox *dynamicBrickContentSpBx_217;
//    QLabel *dynamicBrickMaskLbl_217;
//    QSpinBox *dynamicBrickMaskSpBx_217;
//    QLabel *dynamicBrickContentLbl_218;
//    QSpinBox *dynamicBrickContentSpBx_218;
//    QLabel *dynamicBrickMaskLbl_218;
//    QSpinBox *dynamicBrickMaskSpBx_218;
//    QLabel *dynamicBrickContentLbl_219;
//    QSpinBox *dynamicBrickContentSpBx_219;
//    QLabel *dynamicBrickMaskLbl_219;
//    QSpinBox *dynamicBrickMaskSpBx_219;
//    QLabel *dynamicBrickContentLbl_220;
//    QSpinBox *dynamicBrickContentSpBx_220;
//    QLabel *dynamicBrickMaskLbl_220;
//    QSpinBox *dynamicBrickMaskSpBx_220;
//    QLabel *dynamicBrickContentLbl_221;
//    QSpinBox *dynamicBrickContentSpBx_221;
//    QLabel *dynamicBrickMaskLbl_221;
//    QSpinBox *dynamicBrickMaskSpBx_221;
//    QLabel *dynamicBrickContentLbl_222;
//    QSpinBox *dynamicBrickContentSpBx_222;
//    QLabel *dynamicBrickMaskLbl_222;
//    QSpinBox *dynamicBrickMaskSpBx_222;
//    QLabel *dynamicBrickContentLbl_223;
//    QSpinBox *dynamicBrickContentSpBx_223;
//    QLabel *dynamicBrickMaskLbl_223;
//    QSpinBox *dynamicBrickMaskSpBx_223;
//    QLabel *dynamicBrickContentLbl_224;
//    QSpinBox *dynamicBrickContentSpBx_224;
//    QLabel *dynamicBrickMaskLbl_224;
//    QSpinBox *dynamicBrickMaskSpBx_224;
//    QLabel *dynamicBrickContentLbl_225;
//    QSpinBox *dynamicBrickContentSpBx_225;
//    QLabel *dynamicBrickMaskLbl_225;
//    QSpinBox *dynamicBrickMaskSpBx_225;
//    QLabel *dynamicBrickContentLbl_226;
//    QSpinBox *dynamicBrickContentSpBx_226;
//    QLabel *dynamicBrickMaskLbl_226;
//    QSpinBox *dynamicBrickMaskSpBx_226;
//    QLabel *dynamicBrickContentLbl_227;
//    QSpinBox *dynamicBrickContentSpBx_227;
//    QLabel *dynamicBrickMaskLbl_227;
//    QSpinBox *dynamicBrickMaskSpBx_227;
//    QLabel *dynamicBrickContentLbl_228;
//    QSpinBox *dynamicBrickContentSpBx_228;
//    QLabel *dynamicBrickMaskLbl_228;
//    QSpinBox *dynamicBrickMaskSpBx_228;
//    QLabel *dynamicBrickContentLbl_229;
//    QSpinBox *dynamicBrickContentSpBx_229;
//    QLabel *dynamicBrickMaskLbl_229;
//    QSpinBox *dynamicBrickMaskSpBx_229;
//    QLabel *dynamicBrickContentLbl_230;
//    QSpinBox *dynamicBrickContentSpBx_230;
//    QLabel *dynamicBrickMaskLbl_230;
//    QSpinBox *dynamicBrickMaskSpBx_230;
//    QLabel *dynamicBrickContentLbl_231;
//    QSpinBox *dynamicBrickContentSpBx_231;
//    QLabel *dynamicBrickMaskLbl_231;
//    QSpinBox *dynamicBrickMaskSpBx_231;
//    QLabel *dynamicBrickContentLbl_232;
//    QSpinBox *dynamicBrickContentSpBx_232;
//    QLabel *dynamicBrickMaskLbl_232;
//    QSpinBox *dynamicBrickMaskSpBx_232;
//    QLabel *dynamicBrickContentLbl_233;
//    QSpinBox *dynamicBrickContentSpBx_233;
//    QLabel *dynamicBrickMaskLbl_233;
//    QSpinBox *dynamicBrickMaskSpBx_233;
//    QLabel *dynamicBrickContentLbl_234;
//    QSpinBox *dynamicBrickContentSpBx_234;
//    QLabel *dynamicBrickMaskLbl_234;
//    QSpinBox *dynamicBrickMaskSpBx_234;
//    QLabel *dynamicBrickContentLbl_235;
//    QSpinBox *dynamicBrickContentSpBx_235;
//    QLabel *dynamicBrickMaskLbl_235;
//    QSpinBox *dynamicBrickMaskSpBx_235;
//    QLabel *dynamicBrickContentLbl_236;
//    QSpinBox *dynamicBrickContentSpBx_236;
//    QLabel *dynamicBrickMaskLbl_236;
//    QSpinBox *dynamicBrickMaskSpBx_236;
//    QLabel *dynamicBrickContentLbl_237;
//    QSpinBox *dynamicBrickContentSpBx_237;
//    QLabel *dynamicBrickMaskLbl_237;
//    QSpinBox *dynamicBrickMaskSpBx_237;
//    QLabel *dynamicBrickContentLbl_238;
//    QSpinBox *dynamicBrickContentSpBx_238;
//    QLabel *dynamicBrickMaskLbl_238;
//    QSpinBox *dynamicBrickMaskSpBx_238;
//    QLabel *dynamicBrickContentLbl_239;
//    QSpinBox *dynamicBrickContentSpBx_239;
//    QLabel *dynamicBrickMaskLbl_239;
//    QSpinBox *dynamicBrickMaskSpBx_239;
//    QLabel *dynamicBrickContentLbl_240;
//    QSpinBox *dynamicBrickContentSpBx_240;
//    QLabel *dynamicBrickMaskLbl_240;
//    QSpinBox *dynamicBrickMaskSpBx_240;
//    QLabel *dynamicBrickContentLbl_241;
//    QSpinBox *dynamicBrickContentSpBx_241;
//    QLabel *dynamicBrickMaskLbl_241;
//    QSpinBox *dynamicBrickMaskSpBx_241;
//    QLabel *dynamicBrickContentLbl_242;
//    QSpinBox *dynamicBrickContentSpBx_242;
//    QLabel *dynamicBrickMaskLbl_242;
//    QSpinBox *dynamicBrickMaskSpBx_242;
//    QLabel *dynamicBrickContentLbl_243;
//    QSpinBox *dynamicBrickContentSpBx_243;
//    QLabel *dynamicBrickMaskLbl_243;
//    QSpinBox *dynamicBrickMaskSpBx_243;
//    QLabel *dynamicBrickContentLbl_244;
//    QSpinBox *dynamicBrickContentSpBx_244;
//    QLabel *dynamicBrickMaskLbl_244;
//    QSpinBox *dynamicBrickMaskSpBx_244;
//    QLabel *dynamicBrickContentLbl_245;
//    QSpinBox *dynamicBrickContentSpBx_245;
//    QLabel *dynamicBrickMaskLbl_245;
//    QSpinBox *dynamicBrickMaskSpBx_245;
//    QLabel *dynamicBrickContentLbl_246;
//    QSpinBox *dynamicBrickContentSpBx_246;
//    QLabel *dynamicBrickMaskLbl_246;
//    QSpinBox *dynamicBrickMaskSpBx_246;
//    QLabel *dynamicBrickContentLbl_247;
//    QSpinBox *dynamicBrickContentSpBx_247;
//    QLabel *dynamicBrickMaskLbl_247;
//    QSpinBox *dynamicBrickMaskSpBx_247;
//    QLabel *dynamicBrickContentLbl_248;
//    QSpinBox *dynamicBrickContentSpBx_248;
//    QLabel *dynamicBrickMaskLbl_248;
//    QSpinBox *dynamicBrickMaskSpBx_248;
//    QLabel *dynamicBrickContentLbl_249;
//    QSpinBox *dynamicBrickContentSpBx_249;
//    QLabel *dynamicBrickMaskLbl_249;
//    QSpinBox *dynamicBrickMaskSpBx_249;
//    QLabel *dynamicBrickContentLbl_250;
//    QSpinBox *dynamicBrickContentSpBx_250;
//    QLabel *dynamicBrickMaskLbl_250;
//    QSpinBox *dynamicBrickMaskSpBx_250;
//    QLabel *dynamicBrickContentLbl_251;
//    QSpinBox *dynamicBrickContentSpBx_251;
//    QLabel *dynamicBrickMaskLbl_251;
//    QSpinBox *dynamicBrickMaskSpBx_251;
//    QLabel *dynamicBrickContentLbl_252;
//    QSpinBox *dynamicBrickContentSpBx_252;
//    QLabel *dynamicBrickMaskLbl_252;
//    QSpinBox *dynamicBrickMaskSpBx_252;
//    QLabel *dynamicBrickContentLbl_253;
//    QSpinBox *dynamicBrickContentSpBx_253;
//    QLabel *dynamicBrickMaskLbl_253;
//    QSpinBox *dynamicBrickMaskSpBx_253;
//    QLabel *dynamicBrickContentLbl_254;
//    QSpinBox *dynamicBrickContentSpBx_254;
//    QLabel *dynamicBrickMaskLbl_254;
//    QSpinBox *dynamicBrickMaskSpBx_254;
//    QLabel *dynamicBrickContentLbl_255;
//    QSpinBox *dynamicBrickContentSpBx_255;
//    QLabel *dynamicBrickMaskLbl_255;
//    QSpinBox *dynamicBrickMaskSpBx_255;

    QLabel *dynamicDataLbl_1;
    QSpinBox *dynamicDataSpBx_1;
    QLabel *dynamicDataLbl_2;
    QSpinBox *dynamicDataSpBx_2;
    QLabel *dynamicDataLbl_3;
    QSpinBox *dynamicDataSpBx_3;
    QLabel *dynamicDataLbl_4;
    QSpinBox *dynamicDataSpBx_4;
    QLabel *dynamicDataLbl_5;
    QSpinBox *dynamicDataSpBx_5;
    QLabel *dynamicDataLbl_6;
    QSpinBox *dynamicDataSpBx_6;
    QLabel *dynamicDataLbl_7;
    QSpinBox *dynamicDataSpBx_7;
    QLabel *dynamicDataLbl_8;
    QSpinBox *dynamicDataSpBx_8;
    QLabel *dynamicDataLbl_9;
    QSpinBox *dynamicDataSpBx_9;
    QLabel *dynamicDataLbl_10;
    QSpinBox *dynamicDataSpBx_10;

//    QLabel *dynamicDataLbl_11;
//    QSpinBox *dynamicDataSpBx_11;
//    QLabel *dynamicDataLbl_12;
//    QSpinBox *dynamicDataSpBx_12;
//    QLabel *dynamicDataLbl_13;
//    QSpinBox *dynamicDataSpBx_13;
//    QLabel *dynamicDataLbl_14;
//    QSpinBox *dynamicDataSpBx_14;
//    QLabel *dynamicDataLbl_15;
//    QSpinBox *dynamicDataSpBx_15;
//    QLabel *dynamicDataLbl_16;
//    QSpinBox *dynamicDataSpBx_16;
//    QLabel *dynamicDataLbl_17;
//    QSpinBox *dynamicDataSpBx_17;
//    QLabel *dynamicDataLbl_18;
//    QSpinBox *dynamicDataSpBx_18;
//    QLabel *dynamicDataLbl_19;
//    QSpinBox *dynamicDataSpBx_19;
//    QLabel *dynamicDataLbl_20;
//    QSpinBox *dynamicDataSpBx_20;
//    QLabel *dynamicDataLbl_21;
//    QSpinBox *dynamicDataSpBx_21;
//    QLabel *dynamicDataLbl_22;
//    QSpinBox *dynamicDataSpBx_22;
//    QLabel *dynamicDataLbl_23;
//    QSpinBox *dynamicDataSpBx_23;
//    QLabel *dynamicDataLbl_24;
//    QSpinBox *dynamicDataSpBx_24;
//    QLabel *dynamicDataLbl_25;
//    QSpinBox *dynamicDataSpBx_25;
//    QLabel *dynamicDataLbl_26;
//    QSpinBox *dynamicDataSpBx_26;
//    QLabel *dynamicDataLbl_27;
//    QSpinBox *dynamicDataSpBx_27;
//    QLabel *dynamicDataLbl_28;
//    QSpinBox *dynamicDataSpBx_28;
//    QLabel *dynamicDataLbl_29;
//    QSpinBox *dynamicDataSpBx_29;
//    QLabel *dynamicDataLbl_30;
//    QSpinBox *dynamicDataSpBx_30;
//    QLabel *dynamicDataLbl_31;
//    QSpinBox *dynamicDataSpBx_31;
//    QLabel *dynamicDataLbl_32;
//    QSpinBox *dynamicDataSpBx_32;
//    QLabel *dynamicDataLbl_33;
//    QSpinBox *dynamicDataSpBx_33;
//    QLabel *dynamicDataLbl_34;
//    QSpinBox *dynamicDataSpBx_34;
//    QLabel *dynamicDataLbl_35;
//    QSpinBox *dynamicDataSpBx_35;
//    QLabel *dynamicDataLbl_36;
//    QSpinBox *dynamicDataSpBx_36;
//    QLabel *dynamicDataLbl_37;
//    QSpinBox *dynamicDataSpBx_37;
//    QLabel *dynamicDataLbl_38;
//    QSpinBox *dynamicDataSpBx_38;
//    QLabel *dynamicDataLbl_39;
//    QSpinBox *dynamicDataSpBx_39;
//    QLabel *dynamicDataLbl_40;
//    QSpinBox *dynamicDataSpBx_40;
//    QLabel *dynamicDataLbl_41;
//    QSpinBox *dynamicDataSpBx_41;
//    QLabel *dynamicDataLbl_42;
//    QSpinBox *dynamicDataSpBx_42;
//    QLabel *dynamicDataLbl_43;
//    QSpinBox *dynamicDataSpBx_43;
//    QLabel *dynamicDataLbl_44;
//    QSpinBox *dynamicDataSpBx_44;
//    QLabel *dynamicDataLbl_45;
//    QSpinBox *dynamicDataSpBx_45;
//    QLabel *dynamicDataLbl_46;
//    QSpinBox *dynamicDataSpBx_46;
//    QLabel *dynamicDataLbl_47;
//    QSpinBox *dynamicDataSpBx_47;
//    QLabel *dynamicDataLbl_48;
//    QSpinBox *dynamicDataSpBx_48;
//    QLabel *dynamicDataLbl_49;
//    QSpinBox *dynamicDataSpBx_49;
//    QLabel *dynamicDataLbl_50;
//    QSpinBox *dynamicDataSpBx_50;
//    QLabel *dynamicDataLbl_51;
//    QSpinBox *dynamicDataSpBx_51;
//    QLabel *dynamicDataLbl_52;
//    QSpinBox *dynamicDataSpBx_52;
//    QLabel *dynamicDataLbl_53;
//    QSpinBox *dynamicDataSpBx_53;
//    QLabel *dynamicDataLbl_54;
//    QSpinBox *dynamicDataSpBx_54;
//    QLabel *dynamicDataLbl_55;
//    QSpinBox *dynamicDataSpBx_55;
//    QLabel *dynamicDataLbl_56;
//    QSpinBox *dynamicDataSpBx_56;
//    QLabel *dynamicDataLbl_57;
//    QSpinBox *dynamicDataSpBx_57;
//    QLabel *dynamicDataLbl_58;
//    QSpinBox *dynamicDataSpBx_58;
//    QLabel *dynamicDataLbl_59;
//    QSpinBox *dynamicDataSpBx_59;
//    QLabel *dynamicDataLbl_60;
//    QSpinBox *dynamicDataSpBx_60;
//    QLabel *dynamicDataLbl_61;
//    QSpinBox *dynamicDataSpBx_61;
//    QLabel *dynamicDataLbl_62;
//    QSpinBox *dynamicDataSpBx_62;
//    QLabel *dynamicDataLbl_63;
//    QSpinBox *dynamicDataSpBx_63;
//    QLabel *dynamicDataLbl_64;
//    QSpinBox *dynamicDataSpBx_64;
//    QLabel *dynamicDataLbl_65;
//    QSpinBox *dynamicDataSpBx_65;
//    QLabel *dynamicDataLbl_66;
//    QSpinBox *dynamicDataSpBx_66;
//    QLabel *dynamicDataLbl_67;
//    QSpinBox *dynamicDataSpBx_67;
//    QLabel *dynamicDataLbl_68;
//    QSpinBox *dynamicDataSpBx_68;
//    QLabel *dynamicDataLbl_69;
//    QSpinBox *dynamicDataSpBx_69;
//    QLabel *dynamicDataLbl_70;
//    QSpinBox *dynamicDataSpBx_70;
//    QLabel *dynamicDataLbl_71;
//    QSpinBox *dynamicDataSpBx_71;
//    QLabel *dynamicDataLbl_72;
//    QSpinBox *dynamicDataSpBx_72;
//    QLabel *dynamicDataLbl_73;
//    QSpinBox *dynamicDataSpBx_73;
//    QLabel *dynamicDataLbl_74;
//    QSpinBox *dynamicDataSpBx_74;
//    QLabel *dynamicDataLbl_75;
//    QSpinBox *dynamicDataSpBx_75;
//    QLabel *dynamicDataLbl_76;
//    QSpinBox *dynamicDataSpBx_76;
//    QLabel *dynamicDataLbl_77;
//    QSpinBox *dynamicDataSpBx_77;
//    QLabel *dynamicDataLbl_78;
//    QSpinBox *dynamicDataSpBx_78;
//    QLabel *dynamicDataLbl_79;
//    QSpinBox *dynamicDataSpBx_79;
//    QLabel *dynamicDataLbl_80;
//    QSpinBox *dynamicDataSpBx_80;
//    QLabel *dynamicDataLbl_81;
//    QSpinBox *dynamicDataSpBx_81;
//    QLabel *dynamicDataLbl_82;
//    QSpinBox *dynamicDataSpBx_82;
//    QLabel *dynamicDataLbl_83;
//    QSpinBox *dynamicDataSpBx_83;
//    QLabel *dynamicDataLbl_84;
//    QSpinBox *dynamicDataSpBx_84;
//    QLabel *dynamicDataLbl_85;
//    QSpinBox *dynamicDataSpBx_85;
//    QLabel *dynamicDataLbl_86;
//    QSpinBox *dynamicDataSpBx_86;
//    QLabel *dynamicDataLbl_87;
//    QSpinBox *dynamicDataSpBx_87;
//    QLabel *dynamicDataLbl_88;
//    QSpinBox *dynamicDataSpBx_88;
//    QLabel *dynamicDataLbl_89;
//    QSpinBox *dynamicDataSpBx_89;
//    QLabel *dynamicDataLbl_90;
//    QSpinBox *dynamicDataSpBx_90;
//    QLabel *dynamicDataLbl_91;
//    QSpinBox *dynamicDataSpBx_91;
//    QLabel *dynamicDataLbl_92;
//    QSpinBox *dynamicDataSpBx_92;
//    QLabel *dynamicDataLbl_93;
//    QSpinBox *dynamicDataSpBx_93;
//    QLabel *dynamicDataLbl_94;
//    QSpinBox *dynamicDataSpBx_94;
//    QLabel *dynamicDataLbl_95;
//    QSpinBox *dynamicDataSpBx_95;
//    QLabel *dynamicDataLbl_96;
//    QSpinBox *dynamicDataSpBx_96;
//    QLabel *dynamicDataLbl_97;
//    QSpinBox *dynamicDataSpBx_97;
//    QLabel *dynamicDataLbl_98;
//    QSpinBox *dynamicDataSpBx_98;
//    QLabel *dynamicDataLbl_99;
//    QSpinBox *dynamicDataSpBx_99;
//    QLabel *dynamicDataLbl_100;
//    QSpinBox *dynamicDataSpBx_100;
//    QLabel *dynamicDataLbl_101;
//    QSpinBox *dynamicDataSpBx_101;
//    QLabel *dynamicDataLbl_102;
//    QSpinBox *dynamicDataSpBx_102;
//    QLabel *dynamicDataLbl_103;
//    QSpinBox *dynamicDataSpBx_103;
//    QLabel *dynamicDataLbl_104;
//    QSpinBox *dynamicDataSpBx_104;
//    QLabel *dynamicDataLbl_105;
//    QSpinBox *dynamicDataSpBx_105;
//    QLabel *dynamicDataLbl_106;
//    QSpinBox *dynamicDataSpBx_106;
//    QLabel *dynamicDataLbl_107;
//    QSpinBox *dynamicDataSpBx_107;
//    QLabel *dynamicDataLbl_108;
//    QSpinBox *dynamicDataSpBx_108;
//    QLabel *dynamicDataLbl_109;
//    QSpinBox *dynamicDataSpBx_109;
//    QLabel *dynamicDataLbl_110;
//    QSpinBox *dynamicDataSpBx_110;
//    QLabel *dynamicDataLbl_111;
//    QSpinBox *dynamicDataSpBx_111;
//    QLabel *dynamicDataLbl_112;
//    QSpinBox *dynamicDataSpBx_112;
//    QLabel *dynamicDataLbl_113;
//    QSpinBox *dynamicDataSpBx_113;
//    QLabel *dynamicDataLbl_114;
//    QSpinBox *dynamicDataSpBx_114;
//    QLabel *dynamicDataLbl_115;
//    QSpinBox *dynamicDataSpBx_115;
//    QLabel *dynamicDataLbl_116;
//    QSpinBox *dynamicDataSpBx_116;
//    QLabel *dynamicDataLbl_117;
//    QSpinBox *dynamicDataSpBx_117;
//    QLabel *dynamicDataLbl_118;
//    QSpinBox *dynamicDataSpBx_118;
//    QLabel *dynamicDataLbl_119;
//    QSpinBox *dynamicDataSpBx_119;
//    QLabel *dynamicDataLbl_120;
//    QSpinBox *dynamicDataSpBx_120;
//    QLabel *dynamicDataLbl_121;
//    QSpinBox *dynamicDataSpBx_121;
//    QLabel *dynamicDataLbl_122;
//    QSpinBox *dynamicDataSpBx_122;
//    QLabel *dynamicDataLbl_123;
//    QSpinBox *dynamicDataSpBx_123;
//    QLabel *dynamicDataLbl_124;
//    QSpinBox *dynamicDataSpBx_124;
//    QLabel *dynamicDataLbl_125;
//    QSpinBox *dynamicDataSpBx_125;
//    QLabel *dynamicDataLbl_126;
//    QSpinBox *dynamicDataSpBx_126;
//    QLabel *dynamicDataLbl_127;
//    QSpinBox *dynamicDataSpBx_127;
//    QLabel *dynamicDataLbl_128;
//    QSpinBox *dynamicDataSpBx_128;
//    QLabel *dynamicDataLbl_129;
//    QSpinBox *dynamicDataSpBx_129;
//    QLabel *dynamicDataLbl_130;
//    QSpinBox *dynamicDataSpBx_130;
//    QLabel *dynamicDataLbl_131;
//    QSpinBox *dynamicDataSpBx_131;
//    QLabel *dynamicDataLbl_132;
//    QSpinBox *dynamicDataSpBx_132;
//    QLabel *dynamicDataLbl_133;
//    QSpinBox *dynamicDataSpBx_133;
//    QLabel *dynamicDataLbl_134;
//    QSpinBox *dynamicDataSpBx_134;
//    QLabel *dynamicDataLbl_135;
//    QSpinBox *dynamicDataSpBx_135;
//    QLabel *dynamicDataLbl_136;
//    QSpinBox *dynamicDataSpBx_136;
//    QLabel *dynamicDataLbl_137;
//    QSpinBox *dynamicDataSpBx_137;
//    QLabel *dynamicDataLbl_138;
//    QSpinBox *dynamicDataSpBx_138;
//    QLabel *dynamicDataLbl_139;
//    QSpinBox *dynamicDataSpBx_139;
//    QLabel *dynamicDataLbl_140;
//    QSpinBox *dynamicDataSpBx_140;
//    QLabel *dynamicDataLbl_141;
//    QSpinBox *dynamicDataSpBx_141;
//    QLabel *dynamicDataLbl_142;
//    QSpinBox *dynamicDataSpBx_142;
//    QLabel *dynamicDataLbl_143;
//    QSpinBox *dynamicDataSpBx_143;
//    QLabel *dynamicDataLbl_144;
//    QSpinBox *dynamicDataSpBx_144;
//    QLabel *dynamicDataLbl_145;
//    QSpinBox *dynamicDataSpBx_145;
//    QLabel *dynamicDataLbl_146;
//    QSpinBox *dynamicDataSpBx_146;
//    QLabel *dynamicDataLbl_147;
//    QSpinBox *dynamicDataSpBx_147;
//    QLabel *dynamicDataLbl_148;
//    QSpinBox *dynamicDataSpBx_148;
//    QLabel *dynamicDataLbl_149;
//    QSpinBox *dynamicDataSpBx_149;
//    QLabel *dynamicDataLbl_150;
//    QSpinBox *dynamicDataSpBx_150;
//    QLabel *dynamicDataLbl_151;
//    QSpinBox *dynamicDataSpBx_151;
//    QLabel *dynamicDataLbl_152;
//    QSpinBox *dynamicDataSpBx_152;
//    QLabel *dynamicDataLbl_153;
//    QSpinBox *dynamicDataSpBx_153;
//    QLabel *dynamicDataLbl_154;
//    QSpinBox *dynamicDataSpBx_154;
//    QLabel *dynamicDataLbl_155;
//    QSpinBox *dynamicDataSpBx_155;
//    QLabel *dynamicDataLbl_156;
//    QSpinBox *dynamicDataSpBx_156;
//    QLabel *dynamicDataLbl_157;
//    QSpinBox *dynamicDataSpBx_157;
//    QLabel *dynamicDataLbl_158;
//    QSpinBox *dynamicDataSpBx_158;
//    QLabel *dynamicDataLbl_159;
//    QSpinBox *dynamicDataSpBx_159;
//    QLabel *dynamicDataLbl_160;
//    QSpinBox *dynamicDataSpBx_160;
//    QLabel *dynamicDataLbl_161;
//    QSpinBox *dynamicDataSpBx_161;
//    QLabel *dynamicDataLbl_162;
//    QSpinBox *dynamicDataSpBx_162;
//    QLabel *dynamicDataLbl_163;
//    QSpinBox *dynamicDataSpBx_163;
//    QLabel *dynamicDataLbl_164;
//    QSpinBox *dynamicDataSpBx_164;
//    QLabel *dynamicDataLbl_165;
//    QSpinBox *dynamicDataSpBx_165;
//    QLabel *dynamicDataLbl_166;
//    QSpinBox *dynamicDataSpBx_166;
//    QLabel *dynamicDataLbl_167;
//    QSpinBox *dynamicDataSpBx_167;
//    QLabel *dynamicDataLbl_168;
//    QSpinBox *dynamicDataSpBx_168;
//    QLabel *dynamicDataLbl_169;
//    QSpinBox *dynamicDataSpBx_169;
//    QLabel *dynamicDataLbl_170;
//    QSpinBox *dynamicDataSpBx_170;
//    QLabel *dynamicDataLbl_171;
//    QSpinBox *dynamicDataSpBx_171;
//    QLabel *dynamicDataLbl_172;
//    QSpinBox *dynamicDataSpBx_172;
//    QLabel *dynamicDataLbl_173;
//    QSpinBox *dynamicDataSpBx_173;
//    QLabel *dynamicDataLbl_174;
//    QSpinBox *dynamicDataSpBx_174;
//    QLabel *dynamicDataLbl_175;
//    QSpinBox *dynamicDataSpBx_175;
//    QLabel *dynamicDataLbl_176;
//    QSpinBox *dynamicDataSpBx_176;
//    QLabel *dynamicDataLbl_177;
//    QSpinBox *dynamicDataSpBx_177;
//    QLabel *dynamicDataLbl_178;
//    QSpinBox *dynamicDataSpBx_178;
//    QLabel *dynamicDataLbl_179;
//    QSpinBox *dynamicDataSpBx_179;
//    QLabel *dynamicDataLbl_180;
//    QSpinBox *dynamicDataSpBx_180;
//    QLabel *dynamicDataLbl_181;
//    QSpinBox *dynamicDataSpBx_181;
//    QLabel *dynamicDataLbl_182;
//    QSpinBox *dynamicDataSpBx_182;
//    QLabel *dynamicDataLbl_183;
//    QSpinBox *dynamicDataSpBx_183;
//    QLabel *dynamicDataLbl_184;
//    QSpinBox *dynamicDataSpBx_184;
//    QLabel *dynamicDataLbl_185;
//    QSpinBox *dynamicDataSpBx_185;
//    QLabel *dynamicDataLbl_186;
//    QSpinBox *dynamicDataSpBx_186;
//    QLabel *dynamicDataLbl_187;
//    QSpinBox *dynamicDataSpBx_187;
//    QLabel *dynamicDataLbl_188;
//    QSpinBox *dynamicDataSpBx_188;
//    QLabel *dynamicDataLbl_189;
//    QSpinBox *dynamicDataSpBx_189;
//    QLabel *dynamicDataLbl_190;
//    QSpinBox *dynamicDataSpBx_190;
//    QLabel *dynamicDataLbl_191;
//    QSpinBox *dynamicDataSpBx_191;
//    QLabel *dynamicDataLbl_192;
//    QSpinBox *dynamicDataSpBx_192;
//    QLabel *dynamicDataLbl_193;
//    QSpinBox *dynamicDataSpBx_193;
//    QLabel *dynamicDataLbl_194;
//    QSpinBox *dynamicDataSpBx_194;
//    QLabel *dynamicDataLbl_195;
//    QSpinBox *dynamicDataSpBx_195;
//    QLabel *dynamicDataLbl_196;
//    QSpinBox *dynamicDataSpBx_196;
//    QLabel *dynamicDataLbl_197;
//    QSpinBox *dynamicDataSpBx_197;
//    QLabel *dynamicDataLbl_198;
//    QSpinBox *dynamicDataSpBx_198;
//    QLabel *dynamicDataLbl_199;
//    QSpinBox *dynamicDataSpBx_199;
//    QLabel *dynamicDataLbl_200;
//    QSpinBox *dynamicDataSpBx_200;
//    QLabel *dynamicDataLbl_201;
//    QSpinBox *dynamicDataSpBx_201;
//    QLabel *dynamicDataLbl_202;
//    QSpinBox *dynamicDataSpBx_202;
//    QLabel *dynamicDataLbl_203;
//    QSpinBox *dynamicDataSpBx_203;
//    QLabel *dynamicDataLbl_204;
//    QSpinBox *dynamicDataSpBx_204;
//    QLabel *dynamicDataLbl_205;
//    QSpinBox *dynamicDataSpBx_205;
//    QLabel *dynamicDataLbl_206;
//    QSpinBox *dynamicDataSpBx_206;
//    QLabel *dynamicDataLbl_207;
//    QSpinBox *dynamicDataSpBx_207;
//    QLabel *dynamicDataLbl_208;
//    QSpinBox *dynamicDataSpBx_208;
//    QLabel *dynamicDataLbl_209;
//    QSpinBox *dynamicDataSpBx_209;
//    QLabel *dynamicDataLbl_210;
//    QSpinBox *dynamicDataSpBx_210;
//    QLabel *dynamicDataLbl_211;
//    QSpinBox *dynamicDataSpBx_211;
//    QLabel *dynamicDataLbl_212;
//    QSpinBox *dynamicDataSpBx_212;
//    QLabel *dynamicDataLbl_213;
//    QSpinBox *dynamicDataSpBx_213;
//    QLabel *dynamicDataLbl_214;
//    QSpinBox *dynamicDataSpBx_214;
//    QLabel *dynamicDataLbl_215;
//    QSpinBox *dynamicDataSpBx_215;
//    QLabel *dynamicDataLbl_216;
//    QSpinBox *dynamicDataSpBx_216;
//    QLabel *dynamicDataLbl_217;
//    QSpinBox *dynamicDataSpBx_217;
//    QLabel *dynamicDataLbl_218;
//    QSpinBox *dynamicDataSpBx_218;
//    QLabel *dynamicDataLbl_219;
//    QSpinBox *dynamicDataSpBx_219;
//    QLabel *dynamicDataLbl_220;
//    QSpinBox *dynamicDataSpBx_220;
//    QLabel *dynamicDataLbl_221;
//    QSpinBox *dynamicDataSpBx_221;
//    QLabel *dynamicDataLbl_222;
//    QSpinBox *dynamicDataSpBx_222;
//    QLabel *dynamicDataLbl_223;
//    QSpinBox *dynamicDataSpBx_223;
//    QLabel *dynamicDataLbl_224;
//    QSpinBox *dynamicDataSpBx_224;
//    QLabel *dynamicDataLbl_225;
//    QSpinBox *dynamicDataSpBx_225;
//    QLabel *dynamicDataLbl_226;
//    QSpinBox *dynamicDataSpBx_226;
//    QLabel *dynamicDataLbl_227;
//    QSpinBox *dynamicDataSpBx_227;
//    QLabel *dynamicDataLbl_228;
//    QSpinBox *dynamicDataSpBx_228;
//    QLabel *dynamicDataLbl_229;
//    QSpinBox *dynamicDataSpBx_229;
//    QLabel *dynamicDataLbl_230;
//    QSpinBox *dynamicDataSpBx_230;
//    QLabel *dynamicDataLbl_231;
//    QSpinBox *dynamicDataSpBx_231;
//    QLabel *dynamicDataLbl_232;
//    QSpinBox *dynamicDataSpBx_232;
//    QLabel *dynamicDataLbl_233;
//    QSpinBox *dynamicDataSpBx_233;
//    QLabel *dynamicDataLbl_234;
//    QSpinBox *dynamicDataSpBx_234;
//    QLabel *dynamicDataLbl_235;
//    QSpinBox *dynamicDataSpBx_235;
//    QLabel *dynamicDataLbl_236;
//    QSpinBox *dynamicDataSpBx_236;
//    QLabel *dynamicDataLbl_237;
//    QSpinBox *dynamicDataSpBx_237;
//    QLabel *dynamicDataLbl_238;
//    QSpinBox *dynamicDataSpBx_238;
//    QLabel *dynamicDataLbl_239;
//    QSpinBox *dynamicDataSpBx_239;
//    QLabel *dynamicDataLbl_240;
//    QSpinBox *dynamicDataSpBx_240;
//    QLabel *dynamicDataLbl_241;
//    QSpinBox *dynamicDataSpBx_241;
//    QLabel *dynamicDataLbl_242;
//    QSpinBox *dynamicDataSpBx_242;
//    QLabel *dynamicDataLbl_243;
//    QSpinBox *dynamicDataSpBx_243;
//    QLabel *dynamicDataLbl_244;
//    QSpinBox *dynamicDataSpBx_244;
//    QLabel *dynamicDataLbl_245;
//    QSpinBox *dynamicDataSpBx_245;
//    QLabel *dynamicDataLbl_246;
//    QSpinBox *dynamicDataSpBx_246;
//    QLabel *dynamicDataLbl_247;
//    QSpinBox *dynamicDataSpBx_247;
//    QLabel *dynamicDataLbl_248;
//    QSpinBox *dynamicDataSpBx_248;
//    QLabel *dynamicDataLbl_249;
//    QSpinBox *dynamicDataSpBx_249;
//    QLabel *dynamicDataLbl_250;
//    QSpinBox *dynamicDataSpBx_250;
//    QLabel *dynamicDataLbl_251;
//    QSpinBox *dynamicDataSpBx_251;
//    QLabel *dynamicDataLbl_252;
//    QSpinBox *dynamicDataSpBx_252;
//    QLabel *dynamicDataLbl_253;
//    QSpinBox *dynamicDataSpBx_253;
//    QLabel *dynamicDataLbl_254;
//    QSpinBox *dynamicDataSpBx_254;
//    QLabel *dynamicDataLbl_255;
//    QSpinBox *dynamicDataSpBx_255;

};

#endif // MAINWINDOW_H
